"use client";
import Image from "next/image"; import PageHero from "../../components/PageHero"; import {MapPin,Phone,ExternalLink,MessageCircle} from "lucide-react"; import {motion} from "framer-motion"; import QuoteForm from "./QuoteForm";
const branches=[
 {name:"สาขาสุพรรณบุรี",shortName:"สุพรรณบุรี",en:"SUPHAN BURI",logo:"/suparerk-logo-suphanburi.jpg",address:"สำนักงานใหญ่ เลขที่ 232/9 หมู่ที่ 4 ตำบลสนามชัย อำเภอเมืองสุพรรณบุรี จังหวัดสุพรรณบุรี",phone:"086-321-5445",map:"https://maps.app.goo.gl/tddg4Y9Gv5Dd25cX8?g_st=il",embed:"https://www.google.com/maps?q=14.473345,100.1346707&z=16&output=embed"},
 {name:"สาขากาญจนบุรี",shortName:"กาญจนบุรี",en:"KANCHANABURI",logo:"/suparerk-logo-kanchanaburi.jpg",address:"สำนักงานสาขา (1) เลขที่ 1089 หมู่ที่ 4 ตำบลท่าม่วง อำเภอท่าม่วง จังหวัดกาญจนบุรี",phone:"080-373-2231",map:"https://maps.app.goo.gl/jTfe5Rd5fkLsmCnz8?g_st=il",embed:"https://www.google.com/maps?q=Suparerk%20Steel%20Kanchanaburi&z=15&output=embed"}
];
export default function Contact(){return <main><PageHero eyebrow="CONTACT US" title="ติดต่อเรา" desc="ติดต่อฝ่ายขาย สอบถามสินค้า ขอใบเสนอราคา หรือเลือกสาขาที่สะดวกสำหรับการเดินทาง"/>
<section className="mx-auto max-w-7xl px-4 sm:px-6 py-12 sm:py-16 lg:py-20"><div className="grid gap-6 lg:grid-cols-2">{branches.map((b,i)=><motion.article key={b.en} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}} className="overflow-hidden border bg-white"><div className="relative aspect-[16/9] bg-white"><Image src={b.logo} alt={b.name} fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-contain scale-[.82]"/></div><div className="p-5 sm:p-7"><p className="text-xs font-black tracking-[.2em] text-[#8b352d]">{b.en}</p><h2 className="mt-2 text-3xl font-black">{b.name}</h2><div className="mt-5 flex gap-3 border-y border-zinc-200 py-5 lg:min-h-[128px]"><MapPin size={26} className="mt-1 shrink-0 fill-[#8b352d] text-[#8b352d]"/><p className="text-sm leading-7 text-zinc-700">{b.address}</p></div><div className="mt-5 overflow-hidden border bg-zinc-100"><iframe title={`Google Maps ${b.name}`} src={b.embed} width="100%" height="300" loading="lazy" referrerPolicy="no-referrer-when-downgrade" className="block"/></div><a href={b.map} target="_blank" rel="noreferrer" className="mt-3 flex min-h-12 w-full items-center justify-center gap-2 bg-[#8b352d] px-5 py-3 text-sm font-black text-white"><MapPin size={17}/> เปิดเส้นทางใน Google Maps <ExternalLink size={15}/></a><a href={`tel:${b.phone.replace(/-/g,"")}`} className="mt-4 flex min-h-24 items-center gap-4 border-y border-zinc-200 px-2 py-4 text-left text-zinc-800"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-full bg-[#8b352d]/10"><Phone size={29} className="fill-[#a02f2b] text-[#a02f2b]"/></span><span><small className="font-bold text-zinc-600">เบอร์โทรศัพท์ (สาขา{b.shortName})</small><strong className="mt-1 block text-2xl font-black tracking-wide text-[#a02f2b]">{b.phone}</strong></span></a><div className="mt-3 grid grid-cols-3 gap-2"><a href="https://lin.ee/Yurg5Hy" target="_blank" rel="noopener noreferrer" className="flex min-h-20 flex-col items-center justify-center gap-1.5 border border-zinc-200 bg-white p-2 text-center text-xs font-black text-zinc-800 shadow-sm"><Image src="/line-logo.svg" alt="" width={22} height={22}/><span>LINE<br/><small className="font-normal text-zinc-500">สาขา{b.shortName}</small></span></a><a href={`tel:${b.phone.replace(/-/g,"")}`} className="flex min-h-20 flex-col items-center justify-center gap-1.5 border border-zinc-200 bg-white p-2 text-center text-xs font-black text-zinc-800 shadow-sm"><Phone size={22}/><span>โทรเลย</span></a><a href="https://lin.ee/Yurg5Hy" target="_blank" rel="noopener noreferrer" className="flex min-h-20 flex-col items-center justify-center gap-1.5 border border-zinc-200 bg-white p-2 text-center text-xs font-black text-zinc-800 shadow-sm"><MessageCircle size={22}/><span>แชทสอบถาม</span></a></div></div></motion.article>)}</div>
<div className="mt-12 grid gap-8 bg-[#202124] p-5 sm:p-8 text-white lg:grid-cols-[.8fr_1.2fr] lg:p-12"><div><p className="text-xs font-black tracking-[.2em] text-[#c46b60]">SALES & SOCIAL</p><h2 className="mt-3 text-3xl font-black">ช่องทางติดต่อทั้งหมด</h2><p className="mt-5 leading-7 text-zinc-300">Facebook, LINE Official Account, TikTok และช่องทางบริษัท</p><div className="mt-7 space-y-3"><a href="tel:035569333" className="flex items-center gap-3 font-black"><Phone size={18} className="text-[#c46b60]"/> 035-569-333</a><a href="https://linktr.ee/suparerksteel" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 bg-[#8b352d] px-5 py-3 font-black">เปิดช่องทางติดต่อ <ExternalLink size={16}/></a></div></div>
<div className="border border-white/10 bg-white/5 p-5 sm:p-7"><h3 className="text-2xl font-black">ขอใบเสนอราคา</h3><p className="mt-2 text-sm text-zinc-400">กรอกรายละเอียดเบื้องต้นเพื่อเตรียมข้อมูลสำหรับติดต่อฝ่ายขาย</p><QuoteForm /></div></div></section></main>}
