"use client";
import Image from "next/image"; import PageHero from "../../components/PageHero"; import {MapPin,Phone,ExternalLink,Send} from "lucide-react"; import {motion} from "framer-motion";
const branches=[
 {name:"สาขาสุพรรณบุรี",en:"SUPHAN BURI",logo:"/suparerk-logo-suphanburi.jpg",map:"https://maps.app.goo.gl/tddg4Y9Gv5Dd25cX8?g_st=il",embed:"https://www.google.com/maps?q=14.473345,100.1346707&z=16&output=embed"},
 {name:"สาขากาญจนบุรี",en:"KANCHANABURI",logo:"/suparerk-logo-kanchanaburi.jpg",map:"https://maps.app.goo.gl/jTfe5Rd5fkLsmCnz8?g_st=il",embed:"https://www.google.com/maps?q=Suparerk%20Steel%20Kanchanaburi&z=15&output=embed"}
];
export default function Contact(){return <main><PageHero eyebrow="CONTACT US" title="ติดต่อเรา" desc="ติดต่อฝ่ายขาย สอบถามสินค้า ขอใบเสนอราคา หรือเลือกสาขาที่สะดวกสำหรับการเดินทาง"/>
<section className="mx-auto max-w-7xl px-6 py-20"><div className="grid gap-6 lg:grid-cols-2">{branches.map((b,i)=><motion.article key={b.en} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}} className="overflow-hidden border bg-white"><div className="relative aspect-[16/9] bg-white"><Image src={b.logo} alt={b.name} fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-contain scale-[.82]"/></div><div className="p-7"><p className="text-xs font-black tracking-[.2em] text-[#8b352d]">{b.en}</p><h2 className="mt-2 text-3xl font-black">{b.name}</h2><div className="mt-6 overflow-hidden border bg-zinc-100"><iframe title={`Google Maps ${b.name}`} src={b.embed} width="100%" height="330" loading="lazy" referrerPolicy="no-referrer-when-downgrade" className="block"/></div><a href={b.map} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 bg-[#8b352d] px-5 py-3 font-black text-white"><MapPin size={17}/> เปิดเส้นทางใน Google Maps <ExternalLink size={15}/></a></div></motion.article>)}</div>
<div className="mt-12 grid gap-8 bg-[#202124] p-8 text-white lg:grid-cols-[.8fr_1.2fr] lg:p-12"><div><p className="text-xs font-black tracking-[.2em] text-[#c46b60]">SALES & SOCIAL</p><h2 className="mt-3 text-3xl font-black">ช่องทางติดต่อทั้งหมด</h2><p className="mt-5 leading-7 text-zinc-300">Facebook, LINE Official Account, TikTok และช่องทางบริษัท</p><div className="mt-7 space-y-3"><a href="tel:035569333" className="flex items-center gap-3 font-black"><Phone size={18} className="text-[#c46b60]"/> 035-569-333</a><a href="https://linktr.ee/suparerksteel" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 bg-[#8b352d] px-5 py-3 font-black">เปิดช่องทางติดต่อ <ExternalLink size={16}/></a></div></div>
<div className="border border-white/10 bg-white/5 p-7"><h3 className="text-2xl font-black">ขอใบเสนอราคา</h3><p className="mt-2 text-sm text-zinc-400">กรอกรายละเอียดเบื้องต้นเพื่อเตรียมข้อมูลสำหรับติดต่อฝ่ายขาย</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><input className="bg-white px-4 py-3 text-black outline-none" placeholder="ชื่อ / บริษัท"/><input className="bg-white px-4 py-3 text-black outline-none" placeholder="เบอร์โทร"/><input className="bg-white px-4 py-3 text-black outline-none sm:col-span-2" placeholder="สินค้าที่สนใจ"/><textarea className="min-h-28 bg-white px-4 py-3 text-black outline-none sm:col-span-2" placeholder="รายละเอียดเพิ่มเติม"/></div><button type="button" className="mt-4 inline-flex items-center gap-2 bg-[#8b352d] px-6 py-3 font-black">ส่งคำขอ <Send size={16}/></button></div></div></section></main>}
