"use client";
import { useState } from "react";
import type { ExecutiveItem } from "../../lib/executives";
import { updateExecutives } from "./actions";

const newId = () => globalThis.crypto?.randomUUID?.() || `executive-${Date.now()}`;
const blank = (): ExecutiveItem => ({ id: newId(), name: "", position: "", imageUrl: "", published: true });
const copy = (items: ExecutiveItem[]) => items.map(item => ({ ...item }));
export default function ExecutiveEditor({ items: initialItems, revision: initialRevision }: { items: ExecutiveItem[]; revision: string }) {
  const [items,setItems]=useState(()=>copy(initialItems)); const [saved,setSaved]=useState(()=>copy(initialItems)); const [revision,setRevision]=useState(initialRevision); const [pending,setPending]=useState(false); const [message,setMessage]=useState<{text:string;error:boolean}|null>(null); const dirty=JSON.stringify(items)!==JSON.stringify(saved);
  const update=(id:string,key:keyof ExecutiveItem,value:string|boolean)=>{setItems(current=>current.map(item=>item.id===id?{...item,[key]:value}:item));setMessage(null)};
  const move=(index:number,direction:-1|1)=>setItems(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next});
  async function save(){setPending(true);setMessage(null);try{const result=await updateExecutives(items,revision);if(result.error)setMessage({text:result.error,error:true});else if(result.revision){setRevision(result.revision);setSaved(copy(items));setMessage({text:"บันทึกข้อมูลผู้บริหารแล้ว",error:false})}}catch{setMessage({text:"บันทึกไม่สำเร็จ กรุณาตรวจสอบการเชื่อมต่อหรือเข้าสู่ระบบใหม่",error:true})}finally{setPending(false)}}
  return <section id="executives" className="mt-14 border-t pt-10"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-black">จัดการคณะกรรมการและผู้บริหาร</h2><p className="mt-1 text-sm text-zinc-600">เพิ่มรูป ชื่อ ตำแหน่ง และเรียงลำดับที่แสดงในหน้าเกี่ยวกับเรา</p></div><p className="text-sm text-zinc-500">{items.length} รายการ{dirty&&" · มีข้อมูลที่ยังไม่บันทึก"}</p></div>
  {!items.length&&<p className="rounded-lg border bg-white p-6 text-center text-zinc-600">ยังไม่มีข้อมูล กด “เพิ่มผู้บริหาร” เพื่อเริ่มต้น</p>}
  <form onSubmit={event=>{event.preventDefault();void save()}} className="space-y-5">{items.map((item,index)=><article key={item.id} className="rounded-lg border bg-white p-5 sm:p-7"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h3 className="font-bold">รายการที่ {index+1}</h3><div className="flex gap-4"><button type="button" disabled={pending||index===0} onClick={()=>move(index,-1)} className="text-sm underline disabled:opacity-30">เลื่อนขึ้น</button><button type="button" disabled={pending||index===items.length-1} onClick={()=>move(index,1)} className="text-sm underline disabled:opacity-30">เลื่อนลง</button><button type="button" disabled={pending} onClick={()=>{if(window.confirm("ต้องการลบรายการนี้หรือไม่?"))setItems(current=>current.filter(value=>value.id!==item.id))}} className="text-sm text-red-700 underline">ลบ</button></div></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">ชื่อ-นามสกุล<input required maxLength={160} value={item.name} onChange={event=>update(item.id,"name",event.target.value)} className="mt-2 w-full rounded border p-3 font-normal" placeholder="ชื่อผู้บริหาร"/></label><label className="text-sm font-bold">ตำแหน่ง<textarea required maxLength={300} rows={2} value={item.position} onChange={event=>update(item.id,"position",event.target.value)} className="mt-2 w-full rounded border p-3 font-normal" placeholder="กรรมการผู้จัดการ"/></label><label className="text-sm font-bold sm:col-span-2">URL รูปภาพ<input required maxLength={1000} value={item.imageUrl} onChange={event=>update(item.id,"imageUrl",event.target.value)} className="mt-2 w-full rounded border p-3 font-normal" placeholder="/executives/name.jpg หรือ https://example.com/photo.jpg"/>{item.imageUrl&&<img src={item.imageUrl} alt="ตัวอย่างรูปผู้บริหาร" className="mt-3 h-72 w-full border object-cover object-top"/>}</label><label className="flex items-center gap-3 text-sm font-bold sm:col-span-2"><input type="checkbox" checked={item.published} onChange={event=>update(item.id,"published",event.target.checked)} className="h-5 w-5 accent-[#8b352d]"/>เผยแพร่รายการนี้</label></div></article>)}
  <div className="flex flex-wrap items-center justify-between gap-3"><button type="button" disabled={pending} onClick={()=>setItems(current=>[...current,blank()])} className="rounded border border-[#8b352d] px-5 py-3 text-sm font-bold text-[#8b352d]">+ เพิ่มผู้บริหาร</button><div className="flex flex-wrap items-center gap-4">{message&&<p className={`text-sm ${message.error?"text-red-700":"text-green-700"}`}>{message.text}</p>}<button type="submit" disabled={pending||!dirty} className="rounded bg-[#8b352d] px-5 py-3 text-sm font-bold text-white disabled:opacity-40">{pending?"กำลังบันทึก…":"บันทึกข้อมูล"}</button></div></div></form></section>;
}
