"use client";
import Link from "next/link"; import Image from "next/image"; import {usePathname} from "next/navigation"; import {Menu,X,ChevronDown,ArrowRight} from "lucide-react"; import {useState} from "react"; import {motion,AnimatePresence} from "framer-motion"; import {categories,products} from "../data/products";
const basic=[["/","หน้าแรก"],["/about","เกี่ยวกับเรา"],["/projects","ผลงานและโครงการ"],["/news","ข่าวสาร"],["/downloads","ดาวน์โหลด"]];
export default function Header(){const p=usePathname(),[open,setOpen]=useState(false),[mega,setMega]=useState(false);return <><div className="bg-[#202124] px-6 py-2 text-center text-[10px] font-bold tracking-[.18em] text-zinc-400">SUPARERK STEEL CO., LTD. • STEEL FOR CONSTRUCTION & INDUSTRY</div>
<header className="sticky top-0 z-50 border-b border-white/15 bg-[#8B352D]/95 text-white shadow-lg backdrop-blur-xl" onMouseLeave={()=>setMega(false)}><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6">
<Link href="/" className="group flex items-center gap-3"><motion.div whileHover={{scale:1.03}} className="relative h-14 w-20 overflow-hidden bg-white"><Image src="/suparerk-logo-main.jpg" alt="SUPARERK STEEL" fill sizes="80px" className="object-contain scale-[.9]"/></motion.div><div><b className="text-xl">SUPARERK <span className="text-[#f2c9c3]">STEEL</span></b><div className="text-[9px] font-bold tracking-[.2em] text-white/65">ศุภฤกษ์ สตีล จำกัด</div></div></Link>
<nav className="hidden h-full items-center gap-5 lg:flex">{basic.slice(0,2).map(([h,n])=><Nav key={h} h={h} n={n} active={p===h}/>)}
<button onMouseEnter={()=>setMega(true)} onClick={()=>setMega(!mega)} className="relative flex h-full items-center gap-1 text-sm font-black text-white/90 transition hover:text-white">สินค้าและบริการ <ChevronDown size={15} className={"transition "+(mega?"rotate-180":"")}/>{(p.startsWith("/products")||p.startsWith("/services"))&&<motion.span layoutId="navline" className="absolute bottom-0 left-0 h-[3px] w-full bg-white"/>}</button>
{basic.slice(2).map(([h,n])=><Nav key={h} h={h} n={n} active={p===h}/>)}<Link href="/contact" className="bg-white px-5 py-3 text-sm font-black text-[#8b352d] transition hover:bg-[#202124] hover:text-white">ติดต่อเรา</Link></nav><button className="lg:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>
<AnimatePresence>{mega&&<motion.div initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.22}} onMouseEnter={()=>setMega(true)} className="absolute left-0 right-0 top-full hidden border-y bg-white text-[#202124] shadow-2xl lg:block"><div className="mx-auto max-w-7xl px-6 py-8"><div className="mb-6 flex items-center justify-between border-b pb-5"><div><p className="text-xs font-black tracking-[.2em] text-[#8b352d]">PRODUCT CATALOG</p><h3 className="mt-1 text-2xl font-black">สินค้าเหล็กครบทุกหมวด</h3></div><div><Link href="/products" className="font-black text-[#8b352d]">สินค้าทั้งหมด →</Link><Link href="/services" className="ml-6 font-black text-[#8b352d]">บริการ →</Link></div></div><div className="grid grid-cols-5 gap-7">{categories.map(cat=><div key={cat}><b className="text-sm">{cat}</b><div className="mt-4 space-y-2">{products.filter(x=>x.category===cat).map(x=><Link onClick={()=>setMega(false)} key={x.slug} href={`/products/${x.slug}`} className="group flex items-center justify-between text-xs leading-5 text-zinc-500 transition hover:text-[#8b352d]">{x.name}<ArrowRight size={12} className="opacity-0 group-hover:opacity-100"/></Link>)}</div></div>)}</div></div></motion.div>}</AnimatePresence>
<AnimatePresence>{open&&<motion.nav initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="max-h-[75vh] overflow-y-auto border-t border-white/15 bg-[#8b352d] px-6 lg:hidden"><Link href="/products" onClick={()=>setOpen(false)} className="block border-b border-white/15 py-4 font-black">สินค้าทั้งหมด</Link>{categories.map(cat=><div key={cat}><p className="pt-4 text-xs font-black text-[#f2c9c3]">{cat}</p>{products.filter(x=>x.category===cat).map(x=><Link key={x.slug} href={`/products/${x.slug}`} onClick={()=>setOpen(false)} className="block border-b border-white/10 py-3 pl-3 text-sm text-white/85">{x.name}</Link>)}</div>)}<Link href="/services" onClick={()=>setOpen(false)} className="block py-4 font-black">บริการ</Link><Link href="/contact" onClick={()=>setOpen(false)} className="block pb-5 font-black">ติดต่อเรา</Link></motion.nav>}</AnimatePresence></header></>}
function Nav({h,n,active}:{h:string,n:string,active:boolean}){return <Link href={h} className="relative flex h-full items-center text-sm font-black text-white/90 transition hover:text-white">{n}{active&&<motion.span layoutId="navline" className="absolute bottom-0 left-0 h-[3px] w-full bg-white"/>}</Link>}
