"use client";
import Link from "next/link"; import {usePathname} from "next/navigation"; import {Menu,X,ChevronDown,ArrowRight} from "lucide-react"; import {useState} from "react"; import {motion,AnimatePresence} from "framer-motion";
const basic=[["/","หน้าแรก"],["/about","เกี่ยวกับเรา"],["/projects","ผลงานและโครงการ"],["/news","ข่าวสาร"],["/downloads","ดาวน์โหลด"]];
const groups=[
 ["เหล็กเสริมคอนกรีต",[["/products/round-bar","เหล็กเส้นกลม RB"],["/products/deformed-bar","เหล็กข้ออ้อย DB"],["/products/wire-mesh","Wire Mesh"]]],
 ["เหล็กรูปพรรณ",[["/products/square-tube","เหล็กกล่องสี่เหลี่ยม"],["/products/rectangular-tube","เหล็กกล่องแบน"],["/products/c-channel","เหล็กตัวซี"],["/products/angle-bar","เหล็กฉาก"]]],
 ["เหล็กท่อ / แผ่น",[["/products/black-pipe","เหล็กท่อดำ"],["/products/galvanized-pipe","ท่อชุบสังกะสี"],["/products/steel-plate","เหล็กแผ่น"]]],
 ["เหล็กโครงสร้าง",[["/products/h-beam","H-Beam"],["/products/i-beam","I-Beam"],["/products/wide-flange","Wide Flange"]]]
];
export default function Header(){const p=usePathname(),[open,setOpen]=useState(false),[mega,setMega]=useState(false);
return <><div className="bg-[#202124] px-6 py-2 text-center text-[10px] font-bold tracking-[.18em] text-zinc-400">SUPARERK STEEL CO., LTD. • STEEL FOR CONSTRUCTION & INDUSTRY</div>
<header className="sticky top-0 z-50 border-b border-black/5 bg-[#faf9f7]/95 backdrop-blur-xl" onMouseLeave={()=>setMega(false)}>
<div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6">
<Link href="/" className="group flex items-center gap-3"><motion.div whileHover={{rotate:-4,scale:1.05}} className="grid h-11 w-11 place-items-center bg-[#8b352d] font-black text-white">SS</motion.div><div><b className="text-xl">SUPARERK <span className="text-[#8b352d]">STEEL</span></b><div className="text-[9px] font-bold tracking-[.2em] text-zinc-500">ศุภฤกษ์ สตีล จำกัด</div></div></Link>
<nav className="hidden h-full items-center gap-5 lg:flex">
{basic.slice(0,2).map(([h,n])=><Nav key={h} h={h} n={n} active={p===h}/>)}
<button onMouseEnter={()=>setMega(true)} onClick={()=>setMega(!mega)} className={"relative flex h-full items-center gap-1 text-sm font-black "+(p.startsWith("/products")||p.startsWith("/services")?"text-[#8b352d]":"hover:text-[#8b352d]")}>สินค้าและบริการ <ChevronDown size={15} className={"transition "+(mega?"rotate-180":"")}/>{(p.startsWith("/products")||p.startsWith("/services"))&&<motion.span layoutId="navline" className="absolute bottom-0 left-0 h-[3px] w-full bg-[#8b352d]"/>}</button>
{basic.slice(2).map(([h,n])=><Nav key={h} h={h} n={n} active={p===h}/>)}
<Link href="/contact" className="bg-[#8b352d] px-5 py-3 text-sm font-black text-white">ติดต่อเรา</Link></nav>
<button className="lg:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>
<AnimatePresence>{mega&&<motion.div initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.22}} onMouseEnter={()=>setMega(true)} className="absolute left-0 right-0 top-full hidden border-y bg-white shadow-2xl lg:block"><div className="mx-auto max-w-7xl px-6 py-9"><div className="mb-7 flex items-center justify-between border-b pb-5"><div><p className="text-xs font-black tracking-[.2em] text-[#8b352d]">PRODUCT & SERVICES</p><h3 className="mt-1 text-2xl font-black">สินค้าและบริการ</h3></div><div className="flex gap-3"><Link href="/products" className="font-black text-[#8b352d]">สินค้าทั้งหมด →</Link><Link href="/services" className="ml-5 font-black text-[#8b352d]">บริการทั้งหมด →</Link></div></div><div className="grid grid-cols-5 gap-8">{groups.map(([title,items]:any)=><div key={title}><b className="text-sm">{title}</b><div className="mt-4 space-y-3">{items.map(([h,n]:any)=><Link onClick={()=>setMega(false)} key={h} href={h} className="group flex items-center justify-between text-sm text-zinc-500 transition hover:text-[#8b352d]">{n}<ArrowRight size={13} className="opacity-0 transition group-hover:translate-x-1 group-hover:opacity-100"/></Link>)}</div></div>)}<div className="border-l pl-8"><b className="text-sm">บริการของเรา</b><div className="mt-4 space-y-3">{[["/services","บริการทั้งหมด"],["/services#warehouse","คลังสินค้าและสต๊อก"],["/services#quotation","เสนอราคาและเอกสาร"],["/services#delivery","บริการจัดส่ง"]].map(([h,n])=><Link onClick={()=>setMega(false)} key={h} href={h} className="block text-sm text-zinc-500 hover:text-[#8b352d]">{n}</Link>)}</div></div></div></div></motion.div>}</AnimatePresence>
<AnimatePresence>{open&&<motion.nav initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden border-t bg-white px-6 lg:hidden"><Link href="/products" onClick={()=>setOpen(false)} className="block border-b py-4 font-black text-[#8b352d]">สินค้า</Link>{groups.flatMap((g:any)=>g[1]).map(([h,n]:any)=><Link key={h} href={h} onClick={()=>setOpen(false)} className="block border-b py-3 pl-4 text-sm">{n}</Link>)}<Link href="/services" onClick={()=>setOpen(false)} className="block border-b py-4 font-black">บริการ</Link>{basic.slice(2).map(([h,n])=><Link key={h} href={h} onClick={()=>setOpen(false)} className="block border-b py-4 font-bold">{n}</Link>)}<Link href="/contact" onClick={()=>setOpen(false)} className="block py-4 font-black">ติดต่อเรา</Link></motion.nav>}</AnimatePresence>
</header></>}
function Nav({h,n,active}:{h:string,n:string,active:boolean}){return <Link href={h} className={"relative flex h-full items-center text-sm font-black transition "+(active?"text-[#8b352d]":"hover:text-[#8b352d]")}>{n}{active&&<motion.span layoutId="navline" className="absolute bottom-0 left-0 h-[3px] w-full bg-[#8b352d]"/>}</Link>}
