"use client";
import Link from "next/link"; import Image from "next/image"; import {ArrowRight,ShieldCheck,Truck,ReceiptText} from "lucide-react"; import type {Product} from "../data/products"; import type {HomeProjectItem} from "../lib/home-projects"; import {motion,useScroll,useTransform} from "framer-motion"; import {Reveal,Stagger,Item,ParallaxPanel} from "./Motion"; import BrandMarquee from "./BrandMarquee"; import FacebookFeeds from "./FacebookFeeds"; import HomeProjects from "./HomeProjects"; import HomeProductStrip from "./HomeProductStrip"; import HomeBranches from "./HomeBranches";
export default function HomeContent({products,projects}:{products:Product[];projects:HomeProjectItem[]}){
 const {scrollYProgress}=useScroll(); const scaleX=useTransform(scrollYProgress,[0,1],[0,1]);
 return <main>
 <motion.div style={{scaleX,transformOrigin:"0%"}} className="fixed left-0 top-0 z-[70] h-[3px] w-full bg-[#b45145]"/>
 <section className="relative overflow-hidden bg-[#19191b] text-white"><Image src="/steel-warehouse-background.jpg" alt="" fill priority sizes="100vw" className="home-hero-background object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-r from-[#19191b]/90 via-[#19191b]/75 to-[#19191b]/60"/><div className="gridbg absolute inset-0 opacity-40"/><motion.div initial={{x:"100%"}} animate={{x:0}} transition={{duration:1.1,ease:[.22,1,.36,1]}} className="absolute right-0 top-0 hidden h-full w-[38%] bg-[#8b352d]/15 lg:block"/>
 <div className="relative z-10 mx-auto grid lg:min-h-[690px] max-w-7xl items-center gap-8 lg:gap-14 px-4 sm:px-6 py-12 sm:py-16 lg:py-20 lg:grid-cols-[1.08fr_.92fr]">
 <div><motion.p initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.6}} className="font-black tracking-[.22em] text-[#c46b60]">SUPARERK STEEL CO., LTD.</motion.p>
 <div className="mt-6 pt-[.3em]"><motion.h1 initial={{y:"110%"}} animate={{y:0}} transition={{duration:.85,ease:[.16,1,.3,1]}} className="text-[clamp(2.5rem,9vw,4.5rem)] font-bold leading-[1.3] tracking-normal sm:text-7xl xl:text-[78px]">ครบเครื่อง</motion.h1></div>
 <div className="pt-[.12em]"><motion.h2 initial={{y:"110%"}} animate={{y:0}} transition={{duration:.85,delay:.12,ease:[.16,1,.3,1]}} className="text-3xl font-bold leading-[1.3] tracking-normal text-[#b45145] sm:text-6xl">เรื่องเหล็ก</motion.h2></div>
 <motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.38,duration:.7}} className="mt-7 max-w-xl text-lg leading-8 text-zinc-300">ศูนย์รวมเหล็กสำหรับงานก่อสร้าง งานโครงสร้าง และภาคอุตสาหกรรม พร้อมสต๊อกสินค้าและบริการจัดส่ง</motion.p>
 <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.5}} className="mt-9 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><Link href="/products" className="group flex items-center justify-center gap-2 bg-[#8b352d] px-7 py-4 font-black">ดูสินค้าทั้งหมด <ArrowRight className="transition group-hover:translate-x-1" size={18}/></Link><a href="https://lin.ee/Yurg5Hy" target="_blank" rel="noopener noreferrer" className="flex items-center justify-center gap-2 rounded-xl bg-[#06C755] px-7 py-4 font-black text-white shadow-md transition hover:bg-[#05b34a]"><Image src="/line-logo.svg" alt="" width={22} height={22}/>ขอใบเสนอราคาผ่าน LINE</a></motion.div></div>
 <ParallaxPanel/></div></section>
 <section aria-label="เลือกโกดัง" className="border-b border-zinc-200 bg-white">
  <div className="mx-auto flex max-w-7xl items-center gap-5 px-4 py-5 sm:px-6">
   <p className="hidden shrink-0 text-sm font-bold text-zinc-600 sm:block">เลือกสาขาใกล้คุณ</p>
   <div className="grid w-full max-w-lg grid-cols-2 gap-3">
    <Link href="/contact#branch-suphanburi" className="group flex min-h-14 items-center justify-center gap-2 border border-[#8b352d]/25 bg-[#8b352d]/5 px-3 py-2 text-sm font-black text-[#8b352d] transition hover:bg-[#8b352d] hover:text-white">
     <span>สาขาสุพรรณบุรี</span><ArrowRight size={16} className="transition group-hover:translate-x-1"/>
    </Link>
    <Link href="/contact#branch-kanchanaburi" className="group flex min-h-14 items-center justify-center gap-2 border border-[#8b352d]/25 bg-[#8b352d]/5 px-3 py-2 text-sm font-black text-[#8b352d] transition hover:bg-[#8b352d] hover:text-white">
     <span>สาขากาญจนบุรี</span><ArrowRight size={16} className="transition group-hover:translate-x-1"/>
    </Link>
   </div>
  </div>
 </section>
 <HomeProductStrip products={products}/>
 <BrandMarquee/>
 <HomeBranches/>
 <HomeProjects projects={projects}/>
 <FacebookFeeds/>
 <section className="bg-[#efeeea]"><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-16 lg:py-24"><Reveal><p className="text-xs font-black tracking-[.18em] text-[#8b352d] sm:text-base">WHY SUPARERK STEEL</p><h2 className="mt-2 max-w-3xl text-2xl font-black leading-tight sm:mt-3 sm:text-4xl lg:text-5xl">มากกว่าการขายเหล็ก<br/>คือความพร้อมในทุกขั้นตอน</h2></Reveal><Stagger className="mt-6 grid gap-3 sm:mt-12 sm:grid-cols-2 sm:gap-6 lg:grid-cols-3">{[[ShieldCheck,"QUALITY","สเปกถูกต้อง","ให้ความสำคัญกับมาตรฐานและคุณภาพสินค้า"],[ReceiptText,"TAX INVOICE","ออกใบกำกับภาษีได้","ออกเอกสารครบถ้วน รองรับลูกค้าทั่วไปและนิติบุคคล"],[Truck,"DELIVERY","พร้อมจัดส่ง","สนับสนุนตั้งแต่เสนอราคาจนถึงจัดส่งสินค้า"]].map(([I,e,t,d]:any)=><Item key={t}><div className="flex h-full items-start gap-4 rounded-xl border border-zinc-200 bg-white p-4 shadow-sm sm:block sm:rounded-none sm:border-x-0 sm:border-b-0 sm:bg-transparent sm:p-0 sm:pt-7 sm:shadow-none"><I size={30} className="mt-1 shrink-0 text-[#8b352d] sm:mt-0 sm:h-[34px] sm:w-[34px]"/><div className="min-w-0"><p className="text-[10px] font-black tracking-[.18em] text-zinc-400 sm:mt-7 sm:text-xs sm:tracking-[.2em]">{e}</p><h3 className="mt-1 text-xl font-black sm:mt-2 sm:text-2xl">{t}</h3><p className="mt-1 text-sm leading-6 text-zinc-600 sm:mt-3 sm:text-base sm:leading-7">{d}</p></div></div></Item>)}</Stagger></div></section>
 <section className="bg-[#202124] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 py-12 sm:py-16 lg:py-24 lg:grid-cols-2"><Reveal><p className="font-black tracking-[.18em] text-[#c46b60]">SINCE 2020</p><h2 className="mt-4 text-3xl font-black leading-tight sm:text-5xl">เติบโตด้วยคุณภาพ<br/>และความเชื่อมั่น</h2></Reveal><Reveal delay={.12}><p className="text-lg leading-9 text-zinc-300">จากจุดเริ่มต้นในจังหวัดสุพรรณบุรี บริษัทพัฒนาทั้งประเภทสินค้า พื้นที่คลัง ระบบจัดส่ง และพื้นที่ให้บริการ เพื่อรองรับลูกค้าที่หลากหลายและการเติบโตในระยะยาว</p><Link href="/about" className="group mt-8 inline-flex items-center gap-3 font-black text-[#d28a80]">เรื่องราวของเรา <ArrowRight className="transition group-hover:translate-x-2"/></Link></Reveal></div></section>
 <section className="relative overflow-hidden bg-[#8b352d] text-white"><motion.div animate={{rotate:360}} transition={{duration:35,repeat:Infinity,ease:"linear"}} className="absolute -right-24 -top-52 h-96 w-96 rounded-full border border-white/10"/><div className="relative mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-7 px-4 sm:px-6 py-16"><Reveal><p className="text-sm font-bold text-[#f0d8d4]">LET'S BUILD TOGETHER</p><h2 className="mt-2 text-3xl font-black sm:text-4xl">ต้องการสินค้าเหล็ก หรือขอใบเสนอราคา?</h2></Reveal><motion.div whileHover={{scale:1.03}} whileTap={{scale:.98}}><Link href="/contact" className="group flex items-center gap-3 bg-white px-8 py-4 font-black text-[#8b352d]">ติดต่อฝ่ายขาย <ArrowRight className="transition group-hover:translate-x-1"/></Link></motion.div></div></section>
 </main>
}
