"use client";
import Link from "next/link"; import Image from "next/image"; import {ArrowRight,ShieldCheck,Truck,PackageCheck} from "lucide-react"; import type {Product} from "../data/products"; import {motion,useScroll,useTransform} from "framer-motion"; import {Reveal,Stagger,Item,ParallaxPanel} from "./Motion"; import BrandMarquee from "./BrandMarquee"; import FacebookFeeds from "./FacebookFeeds";
export default function HomeContent({products}:{products:Product[]}){
 const {scrollYProgress}=useScroll(); const scaleX=useTransform(scrollYProgress,[0,1],[0,1]);
 return <main>
 <motion.div style={{scaleX,transformOrigin:"0%"}} className="fixed left-0 top-0 z-[70] h-[3px] w-full bg-[#b45145]"/>
 <section className="relative overflow-hidden bg-[#19191b] text-white"><div className="gridbg absolute inset-0 opacity-80"/><motion.div initial={{x:"100%"}} animate={{x:0}} transition={{duration:1.1,ease:[.22,1,.36,1]}} className="absolute right-0 top-0 hidden h-full w-[38%] bg-[#8b352d]/15 lg:block"/>
 <div className="relative mx-auto grid lg:min-h-[690px] max-w-7xl items-center gap-8 lg:gap-14 px-4 sm:px-6 py-12 sm:py-16 lg:py-20 lg:grid-cols-[1.08fr_.92fr]">
 <div><motion.p initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.6}} className="font-black tracking-[.22em] text-[#c46b60]">SUPARERK STEEL CO., LTD.</motion.p>
 <div className="mt-6 pt-[.3em]"><motion.h1 initial={{y:"110%"}} animate={{y:0}} transition={{duration:.85,ease:[.16,1,.3,1]}} className="text-[clamp(2.5rem,9vw,4.5rem)] font-bold leading-[1.3] tracking-normal sm:text-7xl xl:text-[78px]">ครบเครื่อง</motion.h1></div>
 <div className="pt-[.12em]"><motion.h2 initial={{y:"110%"}} animate={{y:0}} transition={{duration:.85,delay:.12,ease:[.16,1,.3,1]}} className="text-3xl font-bold leading-[1.3] tracking-normal text-[#b45145] sm:text-6xl">เรื่องเหล็ก</motion.h2></div>
 <motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.38,duration:.7}} className="mt-7 max-w-xl text-lg leading-8 text-zinc-300">ศูนย์รวมเหล็กสำหรับงานก่อสร้าง งานโครงสร้าง และภาคอุตสาหกรรม พร้อมสต๊อกสินค้าและบริการจัดส่ง</motion.p>
 <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.5}} className="mt-9 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><Link href="/products" className="group flex items-center justify-center gap-2 bg-[#8b352d] px-7 py-4 font-black">ดูสินค้าทั้งหมด <ArrowRight className="transition group-hover:translate-x-1" size={18}/></Link><Link href="/contact" className="text-center border border-white/20 bg-white/5 px-7 py-4 font-black transition hover:bg-white hover:text-black">ขอใบเสนอราคา</Link></motion.div></div>
 <ParallaxPanel/></div></section>
 <section className="overflow-hidden border-y border-black/5 bg-[#8b352d] py-4 text-white"><motion.div animate={{x:["0%","-50%"]}} transition={{duration:50,repeat:Infinity,ease:"linear"}} className="flex w-max">{[...products,...products].map((product,i)=><span key={`${product.slug}-${i}`} className="mx-8 whitespace-nowrap text-xs font-black tracking-wider">{product.name} <b className="ml-12 opacity-40">◆</b></span>)}</motion.div></section>
 <section className="mx-auto max-w-7xl px-4 sm:px-6 py-12 sm:py-16 lg:py-24"><Reveal><p className="font-black tracking-[.18em] text-[#8b352d]">PRODUCT RANGE</p><div className="mt-3 flex items-end justify-between"><h2 className="text-3xl font-black sm:text-4xl lg:text-5xl">สินค้าเหล็กสำหรับทุกโครงสร้าง</h2><Link href="/products" className="hidden font-black text-[#8b352d] sm:block">VIEW ALL →</Link></div></Reveal>
 <Stagger className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.slice(0,6).map((product,i)=><Item key={product.slug}><Link href={`/products/${product.slug}`} className="block h-full"><motion.div whileHover={{y:-8}} transition={{duration:.25}} className="group relative h-full overflow-hidden border bg-white p-5 sm:p-7"><motion.div className="absolute bottom-0 left-0 h-1 bg-[#8b352d]" initial={{width:0}} whileInView={{width:"100%"}} viewport={{once:true}} transition={{delay:i*.07,duration:.7}}/><div className="relative -mx-5 -mt-5 aspect-[4/3] overflow-hidden bg-[#c9c9c9] sm:-mx-7 sm:-mt-7"><Image src={product.image} alt={product.name} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover scale-[1.02] transition duration-300 group-hover:scale-[1.08]"/></div><span className="mt-5 inline-block bg-[#202124] px-3 py-1 text-xs font-black text-[#c46b60]">{product.code}</span><h3 className="mt-3 text-xl font-black">{product.name}</h3><p className="mt-3 leading-7 text-zinc-600">{product.short}</p><p className="mt-5 text-sm font-bold text-zinc-500">ราคาเริ่มต้น <strong className="ml-1 text-2xl font-black text-[#8b352d]">฿{product.price.toLocaleString("th-TH")}</strong></p><span className="mt-5 inline-flex items-center gap-2 text-sm font-black text-[#8b352d]">เลือกขนาด <ArrowRight size={15} className="transition group-hover:translate-x-1"/></span></motion.div></Link></Item>)}</Stagger></section>
 <BrandMarquee/>
 <FacebookFeeds/>
 <section className="bg-[#efeeea]"><div className="mx-auto max-w-7xl px-4 sm:px-6 py-12 sm:py-16 lg:py-24"><Reveal><p className="font-black tracking-[.18em] text-[#8b352d]">WHY SUPARERK STEEL</p><h2 className="mt-3 max-w-3xl text-3xl font-black sm:text-4xl lg:text-5xl">มากกว่าการขายเหล็ก<br/>คือความพร้อมในทุกขั้นตอน</h2></Reveal><Stagger className="mt-14 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{[[ShieldCheck,"QUALITY","สเปกถูกต้อง","ให้ความสำคัญกับมาตรฐานและคุณภาพสินค้า"],[PackageCheck,"STOCK","สินค้าหลากหลาย","รองรับลูกค้ารายย่อย ผู้รับเหมา ร้านค้า และโครงการ"],[Truck,"DELIVERY","พร้อมจัดส่ง","สนับสนุนตั้งแต่เสนอราคาจนถึงจัดส่งสินค้า"]].map(([I,e,t,d]:any)=><Item key={t}><div className="border-t border-zinc-300 pt-7"><I size={34} className="text-[#8b352d]"/><p className="mt-8 text-xs font-black tracking-[.2em] text-zinc-400">{e}</p><h3 className="mt-2 text-2xl font-black">{t}</h3><p className="mt-3 leading-7 text-zinc-600">{d}</p></div></Item>)}</Stagger></div></section>
 <section className="bg-[#202124] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 py-12 sm:py-16 lg:py-24 lg:grid-cols-2"><Reveal><p className="font-black tracking-[.18em] text-[#c46b60]">SINCE 2020</p><h2 className="mt-4 text-3xl font-black leading-tight sm:text-5xl">เติบโตด้วยคุณภาพ<br/>และความเชื่อมั่น</h2></Reveal><Reveal delay={.12}><p className="text-lg leading-9 text-zinc-300">จากจุดเริ่มต้นในจังหวัดสุพรรณบุรี บริษัทพัฒนาทั้งประเภทสินค้า พื้นที่คลัง ระบบจัดส่ง และพื้นที่ให้บริการ เพื่อรองรับลูกค้าที่หลากหลายและการเติบโตในระยะยาว</p><Link href="/about" className="group mt-8 inline-flex items-center gap-3 font-black text-[#d28a80]">เรื่องราวของเรา <ArrowRight className="transition group-hover:translate-x-2"/></Link></Reveal></div></section>
 <section className="relative overflow-hidden bg-[#8b352d] text-white"><motion.div animate={{rotate:360}} transition={{duration:35,repeat:Infinity,ease:"linear"}} className="absolute -right-24 -top-52 h-96 w-96 rounded-full border border-white/10"/><div className="relative mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-7 px-4 sm:px-6 py-16"><Reveal><p className="text-sm font-bold text-[#f0d8d4]">LET'S BUILD TOGETHER</p><h2 className="mt-2 text-3xl font-black sm:text-4xl">ต้องการสินค้าเหล็ก หรือขอใบเสนอราคา?</h2></Reveal><motion.div whileHover={{scale:1.03}} whileTap={{scale:.98}}><Link href="/contact" className="group flex items-center gap-3 bg-white px-8 py-4 font-black text-[#8b352d]">ติดต่อฝ่ายขาย <ArrowRight className="transition group-hover:translate-x-1"/></Link></motion.div></div></section>
 </main>
}
