"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";

export type Locale = "th" | "en" | "zh";

const STORAGE_KEY = "suparerk-language";

const translations: Record<Exclude<Locale, "th">, Record<string, string>> = {
  en: {
    "SUPARERK STEEL CO., LTD.": "SUPARERK STEEL CO., LTD.",
    "STEEL FOR CONSTRUCTION & INDUSTRY": "STEEL FOR CONSTRUCTION & INDUSTRY",
    "หน้าแรก": "Home",
    "เกี่ยวกับเรา": "About Us",
    "ข่าวสาร": "News",
    "สินค้า": "Products",
    "ดูสินค้าทั้งหมด": "All Products",
    "สินค้าทั้งหมด": "All Products",
    "ราคาเหล็กวันนี้": "Steel Prices Today",
    "ติดต่อเรา": "Contact Us",
    "รีวิวจากลูกค้า": "Customer Reviews",
    "ขอใบเสนอราคาผ่าน LINE": "Request a Quote on LINE",
    "ขอใบเสนอราคา": "Request a Quote",
    "รายละเอียดสินค้า": "Product Details",
    "ดูรายละเอียดสินค้า →": "View Product Details →",
    "บริการของเรา": "Our Services",
    "เกี่ยวกับ ศุภฤกษ์ สตีล": "About Suparerk Steel",
    "ข่าวสาร กิจกรรม โปรโมชั่น และบทความจาก SUPARERK STEEL": "News, activities, promotions and articles from SUPARERK STEEL",
    "ติดต่อฝ่ายขาย สอบถามสินค้า ขอใบเสนอราคา หรือเลือกสาขาที่สะดวกสำหรับการเดินทาง": "Contact our sales team, ask about products, request a quote, or choose a convenient branch.",
    "รีวิวจริงจาก Google ของทั้งสองสาขา แสดงเฉพาะรีวิวที่ให้ 5 ดาว": "Verified Google reviews from both branches. Only 5-star reviews are shown.",
    "เลือกหมวดสินค้าและดูข้อมูลสินค้าแต่ละประเภท พร้อมภาพประกอบ สเปก และรายละเอียดการใช้งาน": "Browse product categories, specifications, images and usage details.",
    "ร้านเหล็กสุพรรณบุรีและกาญจนบุรี": "Steel supplier in Suphan Buri and Kanchanaburi",
    "ร้านเหล็ก": "Steel Supplier",
    "สุพรรณบุรี": "Suphan Buri",
    "และ": "and ",
    "กาญจนบุรี": "Kanchanaburi",
    "ครบทุกเรื่องเหล็ก": "Everything in Steel",
    "ศูนย์จำหน่ายเหล็กก่อสร้างและเหล็กโครงสร้าง เหล็กเส้น เหล็กกล่อง เหล็กตัวซี H-Beam ท่อเหล็ก เหล็กแผ่น พร้อมสต๊อกสินค้าและบริการจัดส่งทั่วสุพรรณบุรีและกาญจนบุรี": "Your steel supplier for construction and structural steel, rebar, steel tubes, C-channels, H-beams, pipes and steel plates. Stock and delivery across Suphan Buri and Kanchanaburi.",
    "เลือกสาขาใกล้คุณ": "Choose a Nearby Branch",
    "สาขาสุพรรณบุรี": "Suphan Buri Branch",
    "สาขากาญจนบุรี": "Kanchanaburi Branch",
    "สินค้าเหล็กครบทุกหมวด": "Steel Products for Every Project",
    "สินค้าเหล็กหลากหลายประเภทสำหรับงานหลายรูปแบบ": "A wide range of steel products for many applications",
    "ดูสินค้าและบริการทั้งหมด": "View All Products and Services",
    "ติดตามความเคลื่อนไหวของเรา": "Follow Our Updates",
    "ข่าวสาร สินค้า และกิจกรรมล่าสุดจาก SUPARERK STEEL ทั้งสองสาขา": "The latest news, products and activities from both SUPARERK STEEL branches.",
    "เปิด Facebook": "Visit Facebook",
    "เปิด facebook": "Visit Facebook",
    "อ่านเพิ่มเติม": "Read More",
    "ดูทั้งหมด": "View All",
    "ปีที่ก่อตั้ง": "Founded",
    "ทุนจดทะเบียนปัจจุบัน": "Current Registered Capital",
    "จำนวนสาขา": "Branches",
    "คณะกรรมการและผู้บริหาร": "Board and Management",
    "เส้นทางการเติบโต": "Our Journey",
    "เริ่มต้นศุภฤกษ์ สตีล": "Suparerk Steel Is Founded",
    "เพิ่มศักยภาพสินค้าและคลัง": "Expanded Products and Warehousing",
    "ยกระดับการดำเนินงาน": "Improved Operations",
    "ขยายพื้นที่ให้บริการ": "Expanded Service Areas",
    "ผู้จัดจำหน่ายเหล็กครบวงจร": "A Full-Service Steel Supplier",
    "รู้จักเส้นทางการเติบโตของบริษัท ศุภฤกษ์ สตีล จำกัด จากจุดเริ่มต้นในสุพรรณบุรี สู่ผู้จัดจำหน่ายเหล็กที่พร้อมดูแลลูกค้าหลากหลายกลุ่ม": "Learn about Suparerk Steel Co., Ltd., from its beginnings in Suphan Buri to serving a wide range of customers with steel products.",
    "ศูนย์รวมเหล็กที่เติบโตไปพร้อมกับลูกค้า": "Growing with Our Customers",
    "มากกว่าการขายเหล็ก": "More Than Steel Sales",
    "คือความพร้อมในทุกขั้นตอน": "Support at Every Step",
    "สเปกถูกต้อง": "Reliable Specifications",
    "ออกใบกำกับภาษีได้": "Tax Invoices Available",
    "พร้อมจัดส่ง": "Delivery Available",
    "ต้องการสินค้าเหล็ก หรือขอใบเสนอราคา?": "Looking for Steel or a Quote?",
    "ติดต่อฝ่ายขาย": "Contact Sales",
    "DAILY STEEL PRICE": "DAILY STEEL PRICE",
    "ตารางอัปเดตราคารวม": "Updated Steel Price List",
    "อัปเดตล่าสุด": "Last Updated",
    "ยังไม่มีการบันทึกราคาใหม่": "No recent price update",
    "สรุปราคาเหล็กวันนี้": "Steel Price Summary",
    "รายการ": "Product",
    "ราคา": "Price",
    "ขนาด": "Size",
    "รายการขอราคา": "Quote List",
    "เพิ่มในรายการขอราคา": "Add to Quote List",
    "สอบถามราคา": "Contact for Price",
    "ขนาดให้เลือก": "sizes available",
    "มี ": "Available in ",
    " ราคาเริ่มต้น ": "Starting at ",
    "กรุณาติดต่อฝ่ายขายเพื่อสอบถามราคาปัจจุบันของแต่ละขนาด": "Contact our sales team for current prices by size.",
    "หมายเหตุเกี่ยวกับราคา": "Price Notes",
    "กรุณาติดต่อฝ่ายขายเพื่อยืนยันราคา สต๊อกสินค้า ภาษีมูลค่าเพิ่ม และค่าจัดส่งก่อนสั่งซื้อทุกครั้ง": "Please confirm prices, stock, VAT and delivery fees with our sales team before ordering.",
    "PRODUCT INFORMATION": "PRODUCT INFORMATION",
    "ข้อมูลสินค้า": "Product Information",
    "ข้อมูลเบื้องต้น": "Overview",
    "เลือกขนาด": "Select a Size",
    "SIZE & QUOTATION": "SIZE & QUOTATION",
    "ขนาดและการสอบถามราคา": "Sizes and Quotes",
    "เลือกขนาดที่ต้องการแล้วเพิ่มในรายการ เพื่อขอราคาปัจจุบันจากฝ่ายขาย": "Select a size and add it to your quote list to request current pricing.",
    "PRODUCT GALLERY": "PRODUCT GALLERY",
    "ภาพสินค้าจริง": "Product Gallery",
    "SIZE & WEIGHT TABLE": "SIZE & WEIGHT TABLE",
    "ตารางขนาดและน้ำหนัก": "Size and Weight Table",
    "ความยาว": "Length",
    "ความหนา": "Thickness",
    "น้ำหนัก": "Weight",
    "น้ำหนัก ": "Weight ",
    "เหมาะสำหรับงาน": "Suitable For",
    "กรุณาติดต่อฝ่ายขายเพื่อสอบถามราคาปัจจุบัน สต๊อก ภาษีมูลค่าเพิ่ม และค่าจัดส่งก่อนสั่งซื้อ": "Contact our sales team to confirm current prices, stock, VAT and delivery fees before ordering.",
    "เพิ่มเติมในรายการขอราคา": "Add to Quote List",
    "เลือกแล้ว ": "Selected ",
    "รายการ · ": " items · ",
    " ชิ้น": " pieces",
    "รายการสินค้าที่เลือก": "Selected Products",
    "ซ่อนรายการ": "Hide Items",
    "ดูรายการทั้งหมด": "View All Items",
    "ล้างรายการสินค้าที่เลือกทั้งหมด": "Clear Selected Products",
    "ล้างรายการ": "Clear List",
    "ยังไม่ได้เลือกสินค้า — เลือกได้จากหน้ารวมสินค้าหรือหน้ารายละเอียดสินค้า": "No products selected. Choose products from the catalog or product detail pages.",
    "สินค้าที่สนใจ": "Products of Interest",
    "สินค้าที่สนใจ หรือเลือกจากหน้าสินค้า": "Products of interest, or select from the catalog",
    "รายละเอียดเพิ่มเติม": "Additional Details",
    "รายละเอียดเพิ่มเติมเช่น ที่อยู่, เบอร์โทรติดต่อกลับ": "Additional details, such as your address and callback phone number",
    "คัดลอกข้อความ แล้วเปิด LINE เพื่อส่งรายการสินค้าให้ฝ่ายขายได้ทันที": "Copy the message, then open LINE to send your product list to our sales team.",
    "คัดลอกข้อความสำหรับส่ง LINE": "Copy Message for LINE",
    "คัดลอกแล้ว": "Copied",
    "เปิด LINE": "Open LINE",
    "ส่งคำขอ": "Submit Request",
    "SUPHAN BURI (HEADQUARTER)": "SUPHAN BURI (HEAD OFFICE)",
    "KANCHANABURI": "KANCHANABURI",
    "สำนักงานใหญ่": "Head Office",
    "ดูแผนที่": "View Map",
    "ช่องทางติดต่อทั้งหมด": "All Contact Channels",
    "เลขประจำตัวผู้เสียภาษี:": "Tax ID:",
    "สาขา": "Branch",
    "ฝ่ายขายและช่องทางติดต่อ": "Sales and Contact Channels",
    "ช่องทางติดต่อ": "Contact Channels",
    "รายละเอียดการติดต่อ": "Contact Details",
    "รีวิวจาก Google · ดูบน Google Maps": "Google Review · View on Google Maps",
    "ยังไม่พบรีวิว Google ที่มีข้อความและให้ 5 ดาว": "No 5-star Google reviews with text were found.",
    "ยังไม่ได้เชื่อมต่อ Google Business Profile": "Google Business Profile is not connected yet.",
    "ลองตรวจสอบสิทธิ์บัญชี Google และรหัสสาขาในค่าตั้งค่า": "Check your Google account permissions and branch IDs in the settings.",
    "เชื่อมบัญชี Google Business Profile ที่ยืนยันแล้วของร้าน เพื่อดึงรีวิวจริงและกรองเฉพาะ 5 ดาว": "Connect the verified Google Business Profile to show real customer reviews and filter for 5-star ratings.",
    "บริการจำหน่ายสินค้าเหล็ก": "Steel Product Sales",
    "จำหน่ายสินค้าเหล็ก": "Steel Product Sales",
    "คลังสินค้าและสต๊อก": "Warehousing and Stock",
    "เสนอราคาและเอกสาร": "Quotes and Documents",
    "บริการจัดส่ง": "Delivery Service",
    "บริหารสินค้าเพื่อรองรับคำสั่งซื้อของลูกค้า": "We manage inventory to support customer orders.",
    "รองรับการเสนอราคา เอกสารทางการค้า และใบกำกับภาษี": "We provide quotations, trade documents and tax invoices.",
    "จัดเตรียมและขนส่งสินค้าไปยังพื้นที่ของลูกค้า": "We prepare and deliver products to customer locations.",
    "ติดต่อผ่าน LINE": "Contact via LINE",
    "ปิดเมนู": "Close menu",
    "เปิดเมนู": "Open menu",
    "เมนูหลัก": "Main Menu",
    "เหล็กรูปพรรณขึ้นรูปเย็น": "Cold-Formed Steel",
    "เหล็กรูปพรรณรีดร้อน": "Hot-Rolled Steel",
    "เหล็กแผ่น": "Steel Sheets",
    "เหล็กเสริมคอนกรีต": "Reinforcing Steel",
    "สินค้าสำเร็จรูปและฮาร์ดแวร์": "Fabricated Products and Hardware",
    "เหล็กตัวซี มอก.": "TIS C-Channel",
    "เหล็กตัวซีสังกะสี": "Galvanized C-Channel",
    "เหล็กกล่องสี่เหลี่ยม มอก.": "TIS Square Steel Tube",
    "เหล็กกล่องสี่เหลี่ยม JIS": "JIS Square Steel Tube",
    "เหล็กกล่องสี่เหลี่ยมสังกะสี": "Galvanized Square Steel Tube",
    "เหล็กกล่องแบน มอก.": "TIS Rectangular Steel Tube",
    "เหล็กกล่องแบน JIS": "JIS Rectangular Steel Tube",
    "เหล็กกล่องแบนสังกะสี": "Galvanized Rectangular Tube",
    "เหล็กท่อกลมดำ มอก.": "TIS Black Steel Pipe",
    "เหล็กท่อกลมดำ JIS": "JIS Black Steel Pipe",
    "เหล็กเอชบีม มอก.": "TIS H-Beam",
    "เหล็กเอชบีม SYS": "SYS H-Beam",
    "เหล็กไอบีม มอก.": "TIS I-Beam",
    "เหล็กไอบีม SYS": "SYS I-Beam",
    "เหล็กไวด์แฟรงค์ มอก.": "TIS Wide Flange Beam",
    "เหล็กไวด์แฟรงค์ SYS": "SYS Wide Flange Beam",
    "เหล็กชีทไพล์ มอก.": "TIS Steel Sheet Pile",
    "เหล็กชีทไพล์ SYS": "SYS Steel Sheet Pile",
    "เหล็กฉาก มอก.": "TIS Angle Bar",
    "เหล็กรางน้ำ มอก.": "TIS Channel Bar",
    "เหล็กแผ่นดำ มอก.": "TIS Hot-Rolled Steel Plate",
    "เหล็กแผ่นขาว": "Cold-Rolled Steel Sheet",
    "เหล็กแผ่นลาย": "Checkered Steel Plate",
    "เหล็กแผ่นสังกะสี": "Galvanized Steel Sheet",
    "เหล็กปลอกสำเร็จรูป ทิสคอน ซุปเปอร์ลิงค์": "TISCON Superlinks Readymade Stirrups",
    "เหล็กเส้นกลม": "Round Bar",
    "เหล็กข้ออ้อย มอก.": "TIS Deformed Bar",
    "เหล็กข้ออ้อย TATA": "TATA Deformed Bar",
    "ไวร์เมช": "Welded Wire Mesh",
    "ก่อตั้งบริษัท": "Company Founded",
    "2 ตุลาคม 2563": "2 October 2020",
    "5 ล้านบาท": "THB 5 million",
    "2 สาขา": "2 branches",
    "สุพรรณบุรี และ กาญจนบุรี": "Suphan Buri and Kanchanaburi",
    "สำนักงานใหญ่ เลขที่ 232/9 หมู่ที่ 4 ตำบลสนามชัย อำเภอเมืองสุพรรณบุรี จังหวัดสุพรรณบุรี": "Head office: 232/9 Moo 4, Sanam Chai, Mueang Suphan Buri, Suphan Buri",
    "สำนักงานสาขา 00001 เลขที่ 1089 หมู่ที่ 4 ตำบลท่าม่วง อำเภอท่าม่วง จังหวัดกาญจนบุรี": "Branch office: 1089 Moo 4, Tha Muang, Tha Muang, Kanchanaburi",
    "หน้าติดต่อเรา": "Contact Us",
    "จากราคาเมื่อวาน": "from yesterday's price",
    "ราคา / กก.": "Price / kg",
    "มีหลายขนาด": "Multiple sizes available",
    "มีหลายขนาดและความหนา": "Multiple sizes and thicknesses available",
    "โครงหลังคา": "Roof structures",
    "แป": "Purlins",
    "โรงเรือน": "Sheds",
    "งานโครงสร้าง": "Structural work",
    "งานภายนอก": "Outdoor applications",
    "งานประกอบ": "Fabrication",
    "รั้วและประตู": "Fences and gates",
    "เฟอร์นิเจอร์เหล็ก": "Steel furniture",
    "งานต่อเติม": "Renovations",
    "โครงสร้างอาคาร": "Building structures",
    "เสาและคาน": "Columns and beams",
    "งานวิศวกรรม": "Engineering",
    "โครงสร้างเบา": "Light structures",
    "งานตกแต่ง": "Decorative work",
    "ราวและประตู": "Railings and gates",
    "งานระบบ": "Piping systems",
    "ระบบดับเพลิง": "Fire protection systems",
    "งานอุตสาหกรรม": "Industrial applications",
    "อาคาร": "Buildings",
    "โรงงาน": "Factories",
    "โครงสร้างขนาดใหญ่": "Large structures",
    "เสา": "Columns",
    "คาน": "Beams",
    "กำแพงกันดิน": "Retaining walls",
    "แนวป้องกันน้ำ": "Flood barriers",
    "งานฐานราก": "Foundation work",
    "งานโยธา": "Civil engineering",
    "งานเชื่อมประกอบ": "Welding and fabrication",
    "ชั้นวาง": "Shelving",
    "คานรอง": "Support beams",
    "งานผลิต": "Manufacturing",
    "งานเชื่อม": "Welding",
    "ฐานเครื่องจักร": "Machine bases",
    "งานขึ้นรูป": "Forming",
    "ชิ้นส่วนโลหะ": "Metal components",
    "พื้น": "Flooring",
    "ทางเดิน": "Walkways",
    "บันได": "Stairs",
    "งานก่อสร้าง": "Construction",
    "ปลอกเสาและคาน": "Column and beam ties",
    "งานคอนกรีต": "Concrete work",
    "ฐานราก": "Foundations",
    "พื้นคอนกรีต": "Concrete floors",
    "ถนน": "Roads",
    "ลาน": "Yards",
    "งานสำเร็จรูป": "Prefabricated work",
    "ผิวสังกะสี": "Galvanized finish",
    "มาตรฐาน มอก.": "TIS standard",
    "หลายขนาด": "Multiple sizes",
    "หลายหน้าตัด": "Multiple profiles",
    "หลายความหนา": "Multiple thicknesses",
    "ความยาวมาตรฐาน 6 เมตร": "Standard 6-meter length",
    "ตรวจสอบสต๊อกก่อนสั่งซื้อ": "Check stock before ordering",
    "ตรวจสอบสต๊อกกับฝ่ายขาย": "Check stock with sales",
    "สอบถามสต๊อกกับฝ่ายขาย": "Ask sales about stock",
    "เลือกตามแบบวิศวกรรม": "Select according to engineering plans",
    "เลือกตามแบบ": "Select according to plans",
    "สอบถามเกรดและสต๊อก": "Ask about grade and stock",
    "ตรวจสอบสเปกก่อนจัดส่ง": "Confirm specifications before delivery",
    "มีหลายหน้าตัดให้เลือกตามแบบวิศวกรรม": "Available in multiple profiles to suit engineering plans",
    "ก่อตั้งเมื่อวันที่ ": "Founded on ",
    "ทุนจดทะเบียนเริ่มต้น ": "Initial registered capital ",
    "บาท": "baht",
    " ล้านบาท": " million baht",
    "หนา ": "thick ",
    " มม.": " mm",
    " ฟุต": " ft",
    "ลวด ": "Wire ",
    "ช่อง ": "mesh ",
    "กก./": "kg/",
    "กก.": "kg",
    "ข้อมูลสินค้าและ ": "Product Information and ",
    "ที่อยู่": "Address",
    "เบอร์ติดต่อกลับ": "Callback phone number",
    "จาก Google": "from Google",
    "คะแนน": "rating",
    "5 จาก 5 ดาว": "5 out of 5 stars",
    "โปรโมชั่น": "Promotions",
    "บทความ": "Articles",
    "กิจกรรม": "Activities",
    "เลือกดูสินค้า": "Browse Products",
    "สินค้าแนะนำ": "Featured Products",
    "สินค้าทั้งหมด →": "All Products →",
    "คณะกรรมการ": "Board Members",
    "ผู้บริหาร": "Management",
    "ปัจจุบัน": "Present",
    "ก้าวต่อไป": "What's Next",
    "ดำเนินงานในพื้นที่สุพรรณบุรีและท่าม่วง จังหวัดกาญจนบุรี พร้อมพัฒนาระบบโลจิสติกส์เพื่อจัดส่งสินค้าให้ลูกค้าในพื้นที่ต่าง ๆ": "Serving Suphan Buri and Tha Muang, Kanchanaburi, while improving logistics to deliver to customers in surrounding areas.",
    "พัฒนาระบบบริหารต้นทุน สินค้าคงคลัง การขนส่ง และช่องทางการขาย เพื่อเพิ่มประสิทธิภาพและรองรับการเติบโตในระยะยาว": "Improved cost, inventory, transport and sales-channel management to increase efficiency and support long-term growth.",
    "กรุณาติดต่อฝ่ายขายเพื่อสอบถามข้อมูลเพิ่มเติม": "Please contact our sales team for more information.",
    "เปิด Facebook สาขาสุพรรณบุรี": "Open the Suphan Buri branch on Facebook",
    "เปิด Facebook สาขากาญจนบุรี": "Open the Kanchanaburi branch on Facebook",
    "ติดต่อฝ่ายขาย สอบถามสินค้า ขอใบเสนอราคา": "Contact sales, ask about products, or request a quote",
    "คลิกเพื่อโทร": "Call now",
    "โทรศัพท์": "Phone",
    "สินค้าอื่นในหมวดเดียวกัน": "More in This Category",
    "สินค้าใกล้เคียง": "Related Products",
    "คุณอาจสนใจ": "You May Also Like",
    "ดูสินค้า": "View Product",
    "ภาพสินค้าประกอบ": "Product Image",
    "ราคาเริ่มต้น": "Starting Price",
    "เลือกเพิ่ม": "Add Selection",
    "ลบออก": "Remove",
    "ดูบน Google Maps": "View on Google Maps",
    "รีวิวจริงจาก Google": "Verified Google Reviews",
    "เฉพาะรีวิว 5 ดาว": "5-star reviews only",
    "ไม่มีรีวิว": "No reviews available",
    "พร้อมให้บริการ 2 สาขา": "Two branches ready to serve you",
    "เลือกสาขาที่สะดวก และเปิดเส้นทางผ่าน Google Maps ได้ทันที": "Choose a convenient branch and open directions in Google Maps.",
    "แบรนด์สินค้าที่เราจัดจำหน่าย": "Brands We Carry",
    "2 สาขาใกล้คุณ พร้อมบริการ": "Two branches near you, ready to help",
    "ดูเส้นทาง": "Get Directions",
    "เบอร์โทรศัพท์": "Phone",
    "สำรอง": "Alternate",
    "โทรเลย": "Call Now",
    "เปิดเส้นทางใน Google Maps": "Open Directions in Google Maps",
    "เลือก Facebook ของแต่ละสาขา": "Choose a branch Facebook page",
    "เลือกเบอร์โทรศัพท์ของแต่ละสาขา": "Choose a branch phone number",
    "ปิดช่องทางติดต่อ": "Close contact options",
    "เปิดช่องทางติดต่อ": "Open contact options",
    "เบอร์หลัก · แตะเพื่อโทร": "Main line · Tap to call",
    "เบอร์สำรอง · แตะเพื่อโทร": "Alternate line · Tap to call",
    "หมวดหมู่สินค้า": "Product Categories",
    "ผลงานของเรา": "Our Projects",
    "ดูผลงานก่อนหน้า": "Previous projects",
    "ปิดรูปเต็มจอ": "Close full-screen image",
    "เลือกผลงาน": "Choose a project",
    "เหล็กพร้อมส่งจากคลัง": "Steel Ready for Dispatch",
    "จัดส่งเหล็กหน้างาน": "Steel Delivered to Site",
    "คลังสินค้า สาขาสุพรรณบุรี": "Suphan Buri Branch Warehouse",
    "คลังสินค้า สาขากาญจนบุรี": "Kanchanaburi Branch Warehouse",
    "ให้ความสำคัญกับมาตรฐานและคุณภาพสินค้า": "We prioritize product standards and quality.",
    "ออกเอกสารครบถ้วน รองรับลูกค้าทั่วไปและนิติบุคคล": "Complete documentation for individuals and businesses.",
    "สนับสนุนตั้งแต่เสนอราคาจนถึงจัดส่งสินค้า": "Support from quotation through delivery.",
    "เติบโตด้วยคุณภาพ": "Growing through quality",
    "และความเชื่อมั่น": "and trust",
    "เรื่องราวของเรา": "Our Story",
    "สนใจสินค้า": "Interested in this product?",
    "สอบถามสต๊อก สเปก และราคาได้กับฝ่ายขาย": "Contact sales about stock, specifications and pricing.",
    "สนใจ ": "Interested in ",
    "สินค้าทั้งหมด / ": "All Products / ",
    "ภาพประกอบสินค้า": "Product image",
    "น้ำหนักต่อกระสอบ": "Weight per bag",
    "น้ำหนักต่อชิ้น": "Weight per piece",
    "จำนวนต่อกระสอบ": "Pieces per bag",
    "หมายเหตุ: น้ำหนักจริงอาจแตกต่างตามค่าความคลาดเคลื่อนของมาตรฐานและผู้ผลิต กรุณาตรวจสอบสเปก ใบรับรอง และน้ำหนักสินค้าจริงกับฝ่ายขายก่อนใช้คำนวณโครงสร้างหรือสั่งซื้อ": "Note: Actual weight may vary within manufacturer and standard tolerances. Confirm specifications, certificates and actual product weight with sales before structural calculations or ordering.",
    "สินค้าที่เลือก ": "Selected products ",
    "เพิ่มจำนวน ": "Increase quantity for ",
    "ลดจำนวน ": "Decrease quantity for ",
    "นำ ": "Remove ",
    " ออกจากรายการ": " from the list",
    "รายการสินค้า:": "Products:",
    "รายละเอียดเพิ่มเติม:": "Additional details:",
    "ส่งคำขอเรียบร้อยแล้ว": "Your request has been submitted.",
    "ส่งคำขอไม่สำเร็จ กรุณาลองใหม่หรือติดต่อฝ่ายขายโดยตรง": "Could not submit your request. Please try again or contact sales directly.",
    "สาขาสุพรรณบุรี (สำนักงานใหญ่)": "Suphan Buri Branch (Head Office)",
    "Facebook, LINE Official Account, TikTok และช่องทางบริษัท": "Facebook, LINE Official Account, TikTok and other company channels",
    "กรอกรายละเอียดเบื้องต้นเพื่อเตรียมข้อมูลสำหรับติดต่อฝ่ายขาย": "Enter a few details so our sales team can follow up.",
    "ราคา/": "Price/",
    "หน่วย": "unit",
    "ราคาสินค้าอาจเปลี่ยนแปลงตามต้นทุน ปริมาณ สถานที่จัดส่ง และเงื่อนไขการสั่งซื้อ กรุณาติดต่อฝ่ายขายเพื่อยืนยันราคา สต๊อกสินค้า ภาษีมูลค่าเพิ่ม และค่าจัดส่งก่อนสั่งซื้อทุกครั้ง": "Prices may vary by cost, quantity, delivery location and order terms. Please confirm price, stock, VAT and delivery fees with sales before ordering.",
    "พร้อมให้บริการ": "Ready to serve",
    "สินค้านี้ยังไม่มีรูปที่เพิ่มจาก Admin": "No additional product images are available.",
  },
  zh: {
    "SUPARERK STEEL CO., LTD.": "SUPARERK STEEL CO., LTD.",
    "STEEL FOR CONSTRUCTION & INDUSTRY": "建筑与工业用钢材",
    "หน้าแรก": "首页",
    "เกี่ยวกับเรา": "关于我们",
    "ข่าวสาร": "新闻",
    "สินค้า": "产品",
    "ดูสินค้าทั้งหมด": "全部产品",
    "สินค้าทั้งหมด": "全部产品",
    "ราคาเหล็กวันนี้": "今日钢材价格",
    "ติดต่อเรา": "联系我们",
    "รีวิวจากลูกค้า": "客户评价",
    "ขอใบเสนอราคาผ่าน LINE": "通过 LINE 询价",
    "ขอใบเสนอราคา": "申请报价",
    "รายละเอียดสินค้า": "产品详情",
    "ดูรายละเอียดสินค้า →": "查看产品详情 →",
    "บริการของเรา": "我们的服务",
    "เกี่ยวกับ ศุภฤกษ์ สตีล": "关于 SUPARERK STEEL",
    "ข่าวสาร กิจกรรม โปรโมชั่น และบทความจาก SUPARERK STEEL": "SUPARERK STEEL 的新闻、活动、促销与文章",
    "ติดต่อฝ่ายขาย สอบถามสินค้า ขอใบเสนอราคา หรือเลือกสาขาที่สะดวกสำหรับการเดินทาง": "联系销售团队、咨询产品、申请报价，或选择方便前往的门店。",
    "รีวิวจริงจาก Google ของทั้งสองสาขา แสดงเฉพาะรีวิวที่ให้ 5 ดาว": "显示两家分店的 Google 真实评价，仅展示五星评价。",
    "เลือกหมวดสินค้าและดูข้อมูลสินค้าแต่ละประเภท พร้อมภาพประกอบ สเปก และรายละเอียดการใช้งาน": "浏览产品类别、规格、图片和用途详情。",
    "ร้านเหล็กสุพรรณบุรีและกาญจนบุรี": "素攀武里与北碧府钢材供应商",
    "ร้านเหล็ก": "钢材供应商",
    "สุพรรณบุรี": "素攀武里",
    "และ": "与",
    "กาญจนบุรี": "北碧府",
    "ครบทุกเรื่องเหล็ก": "钢材一站式供应",
    "ศูนย์จำหน่ายเหล็กก่อสร้างและเหล็กโครงสร้าง เหล็กเส้น เหล็กกล่อง เหล็กตัวซี H-Beam ท่อเหล็ก เหล็กแผ่น พร้อมสต๊อกสินค้าและบริการจัดส่งทั่วสุพรรณบุรีและกาญจนบุรี": "供应建筑钢材与结构钢材，包括钢筋、方管、C 型钢、H 型钢、钢管和钢板。备有库存并配送至素攀武里与北碧府各地。",
    "เลือกสาขาใกล้คุณ": "选择附近门店",
    "สาขาสุพรรณบุรี": "素攀武里分店",
    "สาขากาญจนบุรี": "北碧府分店",
    "สินค้าเหล็กครบทุกหมวด": "各类钢材产品",
    "สินค้าเหล็กหลากหลายประเภทสำหรับงานหลายรูปแบบ": "适用于多种工程的钢材产品",
    "ดูสินค้าและบริการทั้งหมด": "查看全部产品与服务",
    "ติดตามความเคลื่อนไหวของเรา": "关注我们的动态",
    "ข่าวสาร สินค้า และกิจกรรมล่าสุดจาก SUPARERK STEEL ทั้งสองสาขา": "了解 SUPARERK STEEL 两家分店的最新消息、产品和活动。",
    "เปิด Facebook": "打开 Facebook",
    "เปิด facebook": "打开 Facebook",
    "อ่านเพิ่มเติม": "阅读更多",
    "ดูทั้งหมด": "查看全部",
    "ปีที่ก่อตั้ง": "成立年份",
    "ทุนจดทะเบียนปัจจุบัน": "目前注册资本",
    "จำนวนสาขา": "门店数量",
    "คณะกรรมการและผู้บริหาร": "董事会与管理层",
    "เส้นทางการเติบโต": "发展历程",
    "เริ่มต้นศุภฤกษ์ สตีล": "SUPARERK STEEL 创立",
    "เพิ่มศักยภาพสินค้าและคลัง": "扩充产品与仓储能力",
    "ยกระดับการดำเนินงาน": "提升运营效率",
    "ขยายพื้นที่ให้บริการ": "扩大服务范围",
    "ผู้จัดจำหน่ายเหล็กครบวงจร": "一站式钢材供应商",
    "รู้จักเส้นทางการเติบโตของบริษัท ศุภฤกษ์ สตีล จำกัด จากจุดเริ่มต้นในสุพรรณบุรี สู่ผู้จัดจำหน่ายเหล็กที่พร้อมดูแลลูกค้าหลากหลายกลุ่ม": "了解 SUPARERK STEEL 有限公司从素攀武里起步，成长为服务各类客户的钢材供应商。",
    "ศูนย์รวมเหล็กที่เติบโตไปพร้อมกับลูกค้า": "与客户共同成长",
    "มากกว่าการขายเหล็ก": "不止于钢材销售",
    "คือความพร้อมในทุกขั้นตอน": "全程提供支持",
    "สเปกถูกต้อง": "规格可靠",
    "ออกใบกำกับภาษีได้": "可开具税务发票",
    "พร้อมจัดส่ง": "提供配送服务",
    "ต้องการสินค้าเหล็ก หรือขอใบเสนอราคา?": "需要钢材或报价吗？",
    "ติดต่อฝ่ายขาย": "联系销售",
    "DAILY STEEL PRICE": "今日钢材价格",
    "ตารางอัปเดตราคารวม": "钢材价格表",
    "อัปเดตล่าสุด": "最近更新",
    "ยังไม่มีการบันทึกราคาใหม่": "暂无最新价格记录",
    "สรุปราคาเหล็กวันนี้": "今日钢材价格汇总",
    "รายการ": "产品",
    "ราคา": "价格",
    "ขนาด": "规格",
    "รายการขอราคา": "询价清单",
    "เพิ่มในรายการขอราคา": "加入询价清单",
    "สอบถามราคา": "询价",
    "กรุณาติดต่อฝ่ายขายเพื่อสอบถามราคาปัจจุบันของแต่ละขนาด": "请联系销售团队查询各规格的当前价格。",
    "หมายเหตุเกี่ยวกับราคา": "价格说明",
    "กรุณาติดต่อฝ่ายขายเพื่อยืนยันราคา สต๊อกสินค้า ภาษีมูลค่าเพิ่ม และค่าจัดส่งก่อนสั่งซื้อทุกครั้ง": "下单前请向销售团队确认价格、库存、增值税和配送费用。",
    "PRODUCT INFORMATION": "产品信息",
    "ข้อมูลสินค้า": "产品信息",
    "ข้อมูลเบื้องต้น": "概况",
    "เลือกขนาด": "选择规格",
    "SIZE & QUOTATION": "规格与询价",
    "ขนาดและการสอบถามราคา": "规格与询价",
    "เลือกขนาดที่ต้องการแล้วเพิ่มในรายการ เพื่อขอราคาปัจจุบันจากฝ่ายขาย": "选择所需规格并加入询价清单，以向销售团队查询当前价格。",
    "PRODUCT GALLERY": "产品图库",
    "ภาพสินค้าจริง": "产品图片",
    "SIZE & WEIGHT TABLE": "规格与重量表",
    "ตารางขนาดและน้ำหนัก": "规格与重量表",
    "ความยาว": "长度",
    "ความหนา": "厚度",
    "น้ำหนัก": "重量",
    "เหมาะสำหรับงาน": "适用范围",
    "กรุณาติดต่อฝ่ายขายเพื่อสอบถามราคาปัจจุบัน สต๊อก ภาษีมูลค่าเพิ่ม และค่าจัดส่งก่อนสั่งซื้อ": "下单前请联系销售团队确认当前价格、库存、增值税和配送费用。",
    "เลือกแล้ว ": "已选择 ",
    "รายการ · ": " 项 · ",
    " ชิ้น": " 件",
    "รายการสินค้าที่เลือก": "已选产品",
    "ซ่อนรายการ": "隐藏清单",
    "ดูรายการทั้งหมด": "查看全部",
    "ล้างรายการสินค้าที่เลือกทั้งหมด": "清空已选产品",
    "ล้างรายการ": "清空清单",
    "ยังไม่ได้เลือกสินค้า — เลือกได้จากหน้ารวมสินค้าหรือหน้ารายละเอียดสินค้า": "尚未选择产品。请从产品目录或产品详情页选择。",
    "สินค้าที่สนใจ": "感兴趣的产品",
    "สินค้าที่สนใจ หรือเลือกจากหน้าสินค้า": "填写感兴趣的产品，或从产品目录中选择",
    "รายละเอียดเพิ่มเติม": "补充信息",
    "รายละเอียดเพิ่มเติมเช่น ที่อยู่, เบอร์โทรติดต่อกลับ": "补充信息，例如地址和回电电话号码",
    "คัดลอกข้อความ แล้วเปิด LINE เพื่อส่งรายการสินค้าให้ฝ่ายขายได้ทันที": "复制消息后打开 LINE，即可将产品清单发送给销售团队。",
    "คัดลอกข้อความสำหรับส่ง LINE": "复制 LINE 消息",
    "คัดลอกแล้ว": "已复制",
    "เปิด LINE": "打开 LINE",
    "SUPHAN BURI (HEADQUARTER)": "素攀武里（总部）",
    "KANCHANABURI": "北碧府",
    "สำนักงานใหญ่": "总部",
    "ดูแผนที่": "查看地图",
    "ช่องทางติดต่อทั้งหมด": "全部联系方式",
    "เลขประจำตัวผู้เสียภาษี:": "税号：",
    "ฝ่ายขายและช่องทางติดต่อ": "销售与联系方式",
    "ช่องทางติดต่อ": "联系方式",
    "รายละเอียดการติดต่อ": "联系详情",
    "รีวิวจาก Google · ดูบน Google Maps": "Google 评价 · 在 Google 地图查看",
    "ยังไม่พบรีวิว Google ที่มีข้อความและให้ 5 ดาว": "未找到带有文字的 Google 五星评价。",
    "ยังไม่ได้เชื่อมต่อ Google Business Profile": "尚未连接 Google 商家资料。",
    "ลองตรวจสอบสิทธิ์บัญชี Google และรหัสสาขาในค่าตั้งค่า": "请检查 Google 账号权限和设置中的门店 ID。",
    "เชื่อมบัญชี Google Business Profile ที่ยืนยันแล้วของร้าน เพื่อดึงรีวิวจริงและกรองเฉพาะ 5 ดาว": "连接已验证的 Google 商家资料，以展示真实评价并筛选五星评价。",
    "จำหน่ายสินค้าเหล็ก": "钢材销售",
    "คลังสินค้าและสต๊อก": "仓库与库存",
    "เสนอราคาและเอกสาร": "报价与文件",
    "บริการจัดส่ง": "配送服务",
    "บริหารสินค้าเพื่อรองรับคำสั่งซื้อของลูกค้า": "管理库存以满足客户订单。",
    "รองรับการเสนอราคา เอกสารทางการค้า และใบกำกับภาษี": "提供报价、商业文件和税务发票。",
    "จัดเตรียมและขนส่งสินค้าไปยังพื้นที่ของลูกค้า": "备货并配送至客户所在地。",
    "ปิดเมนู": "关闭菜单",
    "เปิดเมนู": "打开菜单",
    "เมนูหลัก": "主菜单",
    "เหล็กรูปพรรณขึ้นรูปเย็น": "冷弯型钢",
    "เหล็กรูปพรรณรีดร้อน": "热轧型钢",
    "เหล็กแผ่น": "钢板",
    "เหล็กเสริมคอนกรีต": "钢筋混凝土用钢",
    "สินค้าสำเร็จรูปและฮาร์ดแวร์": "成品与五金",
    "เหล็กตัวซี มอก.": "TIS C 型钢",
    "เหล็กตัวซีสังกะสี": "镀锌 C 型钢",
    "เหล็กกล่องสี่เหลี่ยม มอก.": "TIS 方钢管",
    "เหล็กกล่องสี่เหลี่ยม JIS": "JIS 方钢管",
    "เหล็กกล่องสี่เหลี่ยมสังกะสี": "镀锌方钢管",
    "เหล็กกล่องแบน มอก.": "TIS 矩形钢管",
    "เหล็กกล่องแบน JIS": "JIS 矩形钢管",
    "เหล็กกล่องแบนสังกะสี": "镀锌矩形钢管",
    "เหล็กท่อกลมดำ มอก.": "TIS 黑钢管",
    "เหล็กท่อกลมดำ JIS": "JIS 黑钢管",
    "เหล็กเอชบีม มอก.": "TIS H 型钢",
    "เหล็กเอชบีม SYS": "SYS H 型钢",
    "เหล็กไอบีม มอก.": "TIS I 型钢",
    "เหล็กไอบีม SYS": "SYS I 型钢",
    "เหล็กไวด์แฟรงค์ มอก.": "TIS 宽翼缘钢",
    "เหล็กไวด์แฟรงค์ SYS": "SYS 宽翼缘钢",
    "เหล็กชีทไพล์ มอก.": "TIS 钢板桩",
    "เหล็กชีทไพล์ SYS": "SYS 钢板桩",
    "เหล็กฉาก มอก.": "TIS 角钢",
    "เหล็กรางน้ำ มอก.": "TIS 槽钢",
    "เหล็กแผ่นดำ มอก.": "TIS 热轧钢板",
    "เหล็กแผ่นขาว": "冷轧钢板",
    "เหล็กแผ่นลาย": "花纹钢板",
    "เหล็กแผ่นสังกะสี": "镀锌钢板",
    "เหล็กปลอกสำเร็จรูป ทิสคอน ซุปเปอร์ลิงค์": "TISCON 成品箍筋",
    "เหล็กเส้นกลม": "圆钢",
    "เหล็กข้ออ้อย มอก.": "TIS 带肋钢筋",
    "เหล็กข้ออ้อย TATA": "TATA 带肋钢筋",
    "ไวร์เมช": "焊接钢筋网",
    "ก่อตั้งบริษัท": "公司成立",
    "2 ตุลาคม 2563": "2020 年 10 月 2 日",
    "5 ล้านบาท": "500 万泰铢",
    "2 สาขา": "2 家门店",
    "สุพรรณบุรี และ กาญจนบุรี": "素攀武里与北碧府",
    "กรุณาติดต่อฝ่ายขายเพื่อสอบถามข้อมูลเพิ่มเติม": "如需更多信息，请联系销售团队。",
    "โปรโมชั่น": "促销",
    "บทความ": "文章",
    "กิจกรรม": "活动",
    "สินค้าแนะนำ": "推荐产品",
    "สินค้าทั้งหมด →": "全部产品 →",
    "ดูสินค้า": "查看产品",
    "คณะกรรมการ": "董事会成员",
    "ผู้บริหาร": "管理层",
    "ปัจจุบัน": "目前",
    "ก้าวต่อไป": "下一步",
    "พัฒนาระบบบริหารต้นทุน สินค้าคงคลัง การขนส่ง และช่องทางการขาย เพื่อเพิ่มประสิทธิภาพและรองรับการเติบโตในระยะยาว": "优化成本、库存、运输和销售渠道管理，以提升效率并支持长期发展。",
    "ที่อยู่": "地址",
    "เบอร์ติดต่อกลับ": "回电号码",
    "จาก Google": "来自 Google",
    "คะแนน": "评分",
    "5 จาก 5 ดาว": "五星好评",
    "ดูบน Google Maps": "在 Google 地图查看",
    "รีวิวจริงจาก Google": "Google 真实评价",
    "เฉพาะรีวิว 5 ดาว": "仅展示五星评价",
    "ไม่มีรีวิว": "暂无评价",
    "มี ": "",
    "ขนาดให้เลือก": "种规格",
    "หนา ": "厚 ",
    " มม.": " 毫米",
    " ฟุต": " 英尺",
    "ลวด ": "线径",
    "ช่อง ": "网格",
    "กก./": "公斤/",
    "กก.": "公斤",
    "ราคา / กก.": "每公斤价格",
    "พร้อมให้บริการ 2 สาขา": "两家门店竭诚为您服务",
    "เลือกสาขาที่สะดวก และเปิดเส้นทางผ่าน Google Maps ได้ทันที": "选择方便的门店，并在 Google 地图中查看路线。",
    "แบรนด์สินค้าที่เราจัดจำหน่าย": "我们经销的品牌",
    "2 สาขาใกล้คุณ พร้อมบริการ": "两家门店就在附近",
    "ดูเส้นทาง": "查看路线",
    "เบอร์โทรศัพท์": "电话",
    "สำรอง": "备用",
    "โทรเลย": "立即拨打",
    "เปิดเส้นทางใน Google Maps": "在 Google 地图中查看路线",
    "เลือก Facebook ของแต่ละสาขา": "选择门店 Facebook 页面",
    "เลือกเบอร์โทรศัพท์ของแต่ละสาขา": "选择门店电话号码",
    "ปิดช่องทางติดต่อ": "关闭联系选项",
    "เปิดช่องทางติดต่อ": "打开联系选项",
    "เบอร์หลัก · แตะเพื่อโทร": "主号码 · 点击拨打",
    "เบอร์สำรอง · แตะเพื่อโทร": "备用号码 · 点击拨打",
    "หมวดหมู่สินค้า": "产品类别",
    "ผลงานของเรา": "项目案例",
    "ดูผลงานก่อนหน้า": "上一个项目",
    "ปิดรูปเต็มจอ": "关闭全屏图片",
    "เลือกผลงาน": "选择项目",
    "เหล็กพร้อมส่งจากคลัง": "钢材备货待发",
    "จัดส่งเหล็กหน้างาน": "钢材配送至工地",
    "คลังสินค้า สาขาสุพรรณบุรี": "素攀武里门店仓库",
    "คลังสินค้า สาขากาญจนบุรี": "北碧府门店仓库",
    "ให้ความสำคัญกับมาตรฐานและคุณภาพสินค้า": "我们重视产品标准与质量。",
    "ออกเอกสารครบถ้วน รองรับลูกค้าทั่วไปและนิติบุคคล": "提供完整文件，服务个人与企业客户。",
    "สนับสนุนตั้งแต่เสนอราคาจนถึงจัดส่งสินค้า": "从报价到配送，全程提供支持。",
    "เติบโตด้วยคุณภาพ": "以品质成长",
    "และความเชื่อมั่น": "赢得信任",
    "เรื่องราวของเรา": "我们的故事",
    "สนใจสินค้า": "对该产品感兴趣？",
    "สอบถามสต๊อก สเปก และราคาได้กับฝ่ายขาย": "请联系销售团队咨询库存、规格和价格。",
    "สนใจ ": "咨询：",
    "สินค้าทั้งหมด / ": "全部产品 / ",
    "ภาพประกอบสินค้า": "产品示意图",
    "น้ำหนักต่อกระสอบ": "每袋重量",
    "น้ำหนักต่อชิ้น": "每件重量",
    "จำนวนต่อกระสอบ": "每袋数量",
    "หมายเหตุ: น้ำหนักจริงอาจแตกต่างตามค่าความคลาดเคลื่อนของมาตรฐานและผู้ผลิต กรุณาตรวจสอบสเปก ใบรับรอง และน้ำหนักสินค้าจริงกับฝ่ายขายก่อนใช้คำนวณโครงสร้างหรือสั่งซื้อ": "备注：实际重量可能因标准和制造商的公差而有所差异。用于结构计算或订购前，请向销售团队确认规格、证书和实际重量。",
    "สินค้าที่เลือก ": "已选产品 ",
    "เพิ่มจำนวน ": "增加数量：",
    "ลดจำนวน ": "减少数量：",
    "นำ ": "移除",
    " ออกจากรายการ": "从清单中",
    "รายการสินค้า:": "产品清单：",
    "รายละเอียดเพิ่มเติม:": "补充信息：",
    "ส่งคำขอเรียบร้อยแล้ว": "请求已提交。",
    "ส่งคำขอไม่สำเร็จ กรุณาลองใหม่หรือติดต่อฝ่ายขายโดยตรง": "提交请求失败。请重试或直接联系销售团队。",
    "สาขาสุพรรณบุรี (สำนักงานใหญ่)": "素攀武里门店（总部）",
    "Facebook, LINE Official Account, TikTok และช่องทางบริษัท": "Facebook、LINE 官方账号、TikTok 及公司其他渠道",
    "กรอกรายละเอียดเบื้องต้นเพื่อเตรียมข้อมูลสำหรับติดต่อฝ่ายขาย": "填写基本信息，以便销售团队跟进。",
    "ราคา/": "价格/",
    "หน่วย": "单位",
    "ราคาสินค้าอาจเปลี่ยนแปลงตามต้นทุน ปริมาณ สถานที่จัดส่ง และเงื่อนไขการสั่งซื้อ กรุณาติดต่อฝ่ายขายเพื่อยืนยันราคา สต๊อกสินค้า ภาษีมูลค่าเพิ่ม และค่าจัดส่งก่อนสั่งซื้อทุกครั้ง": "价格可能因成本、数量、配送地点和订单条件而异。下单前请联系销售团队确认价格、库存、增值税和配送费用。",
    "พร้อมให้บริการ": "竭诚服务",
    "สินค้านี้ยังไม่มีรูปที่เพิ่มจาก Admin": "暂无其他产品图片。",
  },
};

type LanguageContextValue = { locale: Locale; setLocale: (locale: Locale) => void };
const LanguageContext = createContext<LanguageContextValue>({ locale: "th", setLocale: () => {} });

const textOriginals = new WeakMap<Text, { source: string; rendered: string }>();
const attributeOriginals = new WeakMap<Element, Map<string, { source: string; rendered: string }>>();

function localize(source: string, locale: Locale) {
  if (locale === "th") return source;
  const dictionary = translations[locale];
  const trimmed = source.trim();
  const exact = dictionary[trimmed];
  if (exact !== undefined) return source.replace(trimmed, exact);

  let result = source;
  for (const [thai, translated] of Object.entries(dictionary).sort((a, b) => b[0].length - a[0].length)) {
    if (thai.length < 3 || !result.includes(thai)) continue;
    result = result.split(thai).join(translated);
  }
  return result;
}

function translateTextNode(node: Text, locale: Locale) {
  const current = node.nodeValue ?? "";
  let record = textOriginals.get(node);
  if (!record) {
    record = { source: current, rendered: current };
    textOriginals.set(node, record);
  } else if (current !== record.rendered) {
    record = { source: current, rendered: current };
    textOriginals.set(node, record);
  }
  const next = localize(record.source, locale);
  if (current !== next) {
    record.rendered = next;
    node.nodeValue = next;
  }
}

function translateAttribute(element: Element, attribute: string, locale: Locale) {
  const current = element.getAttribute(attribute);
  if (current === null) return;
  let attributes = attributeOriginals.get(element);
  if (!attributes) { attributes = new Map(); attributeOriginals.set(element, attributes); }
  let record = attributes.get(attribute);
  if (!record) { record = { source: current, rendered: current }; attributes.set(attribute, record); }
  else if (current !== record.rendered) { record = { source: current, rendered: current }; attributes.set(attribute, record); }
  const next = localize(record.source, locale);
  if (next !== current) { record.rendered = next; element.setAttribute(attribute, next); }
}

function translateElementTree(root: Node, locale: Locale) {
  const excluded = "SCRIPT,STYLE,NOSCRIPT,OPTION[data-no-translate], [data-no-translate]";
  const elementRoot = root instanceof Element ? root : root.parentElement;
  if (elementRoot?.closest(excluded)) return;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let node: Node | null;
  while ((node = walker.nextNode())) {
    if (node.parentElement?.closest(excluded)) continue;
    translateTextNode(node as Text, locale);
  }
  const elements = root instanceof Element ? [root, ...Array.from(root.querySelectorAll("[aria-label],[placeholder],[title],[alt]"))] : [];
  for (const element of elements) {
    if (element.closest(excluded)) continue;
    for (const attribute of ["aria-label", "placeholder", "title", "alt"]) translateAttribute(element, attribute, locale);
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("th");
  useEffect(() => {
    const stored = window.localStorage.getItem(STORAGE_KEY);
    if (stored === "en" || stored === "zh" || stored === "th") setLocaleState(stored);
  }, []);

  useEffect(() => {
    document.documentElement.lang = locale === "zh" ? "zh-CN" : locale === "en" ? "en" : "th";
    translateElementTree(document.body, locale);
    const observer = new MutationObserver(records => {
      for (const record of records) {
        if (record.type === "characterData" && record.target instanceof Text) translateTextNode(record.target, locale);
        if (record.type === "attributes" && record.target instanceof Element && record.attributeName) translateAttribute(record.target, record.attributeName, locale);
        for (const added of Array.from(record.addedNodes)) translateElementTree(added, locale);
      }
    });
    observer.observe(document.body, { subtree: true, childList: true, characterData: true, attributes: true, attributeFilter: ["aria-label", "placeholder", "title", "alt"] });
    return () => observer.disconnect();
  }, [locale]);

  const value = useMemo<LanguageContextValue>(() => ({
    locale,
    setLocale: next => { window.localStorage.setItem(STORAGE_KEY, next); setLocaleState(next); },
  }), [locale]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() { return useContext(LanguageContext); }

export function LanguageSwitcher({ compact = false }: { compact?: boolean }) {
  const { locale, setLocale } = useLanguage();
  return <label className={`inline-flex shrink-0 items-center gap-1.5 ${compact ? "text-[10px]" : "text-xs"}`}>
    <span className="sr-only">Language / ภาษา / 语言</span>
    <select data-no-translate value={locale} onChange={event => setLocale(event.target.value as Locale)} aria-label="Language / ภาษา / 语言" className="min-h-8 rounded-md border border-white/30 bg-white/10 px-2 text-white outline-none transition hover:bg-white/20 focus:ring-2 focus:ring-white/70">
      <option value="th" className="bg-white text-[#202124]">ไทย</option><option value="en" className="bg-white text-[#202124]">English</option><option value="zh" className="bg-white text-[#202124]">中文</option>
    </select>
  </label>;
}
