"use client";
import Link from "next/link"; import Image from "next/image"; import {motion} from "framer-motion"; import {ArrowLeft,Check} from "lucide-react"; import type {Product} from "../data/products"; import {Reveal,Stagger,Item} from "./Motion";
import {useState} from "react";
import {getProductSpecifications} from "../lib/product-specifications";
import {productStandards} from "../lib/product-standards";
export default function ProductMotion({product:p}:{product:Product}){const [selectedSize,setSelectedSize]=useState(0);const selectedOption=p.options[selectedSize]??p.options[0];const specifications=getProductSpecifications(p);const standard=productStandards[p.slug];return <>
<section className="bg-[#202124] text-white"><div className="mx-auto max-w-7xl px-4 sm:px-6 py-5"><Link href="/products" className="inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-white"><ArrowLeft size={15}/> สินค้าทั้งหมด / {p.category}</Link></div></section>
<section className="overflow-hidden bg-[#202124] text-white"><div className="mx-auto grid lg:min-h-[610px] max-w-7xl items-center gap-8 lg:gap-14 px-4 sm:px-6 py-16 lg:grid-cols-2">
<div><motion.p initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="font-black tracking-[.2em] text-[#c46b60]">{p.en.toUpperCase()}</motion.p><div className="mt-4 overflow-hidden"><motion.h1 initial={{y:"110%"}} animate={{y:0}} transition={{duration:.75,ease:[.16,1,.3,1]}} className="text-3xl font-black sm:text-5xl lg:text-7xl">{p.name}</motion.h1></div><motion.p initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.22,duration:.65}} className="mt-6 max-w-xl text-lg leading-8 text-zinc-300">{p.short}</motion.p><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.32,duration:.6}} className="mt-6 max-w-md"><label htmlFor="product-size" className="text-sm font-bold text-zinc-300">เลือกขนาด</label><select id="product-size" value={selectedSize} onChange={event=>setSelectedSize(Number(event.target.value))} className="mt-2 w-full border border-white/20 bg-white px-4 py-3 font-bold text-[#202124] outline-none focus:border-[#e47b6e]">{p.options.map((option,index)=><option key={option.size} value={index}>{option.size}</option>)}</select><div className="mt-5 flex items-end justify-between gap-4 border-t border-white/15 pt-5"><span className="pb-1 text-sm font-bold text-zinc-400">ราคา</span><p className="text-4xl font-black text-[#e47b6e]">฿{selectedOption.price.toLocaleString("th-TH")}</p></div></motion.div><motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.45}} className="mt-8 flex flex-col gap-3 text-center sm:flex-row"><a href="https://lin.ee/Yurg5Hy" target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#06C755] px-7 py-4 font-black text-white shadow-md transition hover:bg-[#05b34a]"><Image src="/line-logo.svg" alt="" width={22} height={22}/>ขอใบเสนอราคาผ่าน LINE</a><a href="#detail" className="rounded-3xl border border-white/20 px-7 py-4 font-black">ดูรายละเอียด</a></motion.div></div>
<motion.div initial={{opacity:0,scale:.92,x:35}} animate={{opacity:1,scale:1,x:0}} transition={{duration:.85,ease:[.22,1,.36,1]}} className="relative min-h-[280px] overflow-hidden rounded-3xl border border-white/10 bg-[#c9c9c9] sm:min-h-[440px]"><Image src={p.image} alt={p.name} fill priority sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover scale-[1.02]"/><div className="absolute bottom-5 left-5 bg-[#202124]/90 px-4 py-2 text-xs font-black tracking-[.15em] text-white backdrop-blur">{p.code} • ภาพประกอบสินค้า</div></motion.div>
</div></section>
<section className="border-b bg-white"><div className="mx-auto max-w-5xl px-4 py-10 text-center sm:px-6 sm:py-14"><p className="text-sm font-black tracking-[.16em] text-[#8b352d] sm:text-base">{p.en.toUpperCase()}</p><h2 className="mt-2 text-2xl font-black sm:text-3xl">{p.name}</h2>{standard&&<p className="mx-auto mt-6 max-w-4xl border-y py-5 text-sm font-black leading-7 tracking-wide text-zinc-700 sm:text-base">{standard}</p>}</div></section>
<section id="detail" className="scroll-mt-24 mx-auto grid max-w-7xl gap-8 lg:gap-14 px-4 sm:px-6 py-12 sm:py-16 lg:py-24 lg:grid-cols-[1.1fr_.9fr]"><Reveal><p className="font-black tracking-[.18em] text-[#8b352d]">PRODUCT INFORMATION</p><h2 className="mt-3 text-3xl sm:text-4xl font-black">ข้อมูลสินค้า</h2><p className="mt-7 text-lg leading-9 text-zinc-600">{p.description}</p></Reveal><Reveal delay={.12}><div className="border bg-[#f1f0ed] p-5 sm:p-8"><p className="text-xs font-black tracking-[.18em] text-[#8b352d]">SPECIFICATION</p><h3 className="mt-2 text-2xl font-black">ข้อมูลเบื้องต้น</h3><div className="mt-6 space-y-4">{p.specs.map(s=><p key={s} className="flex gap-3 text-zinc-600"><Check className="shrink-0 text-[#8b352d]" size={19}/>{s}</p>)}</div></div></Reveal></section>
<section className="bg-white"><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-16 lg:py-24"><Reveal><p className="font-black tracking-[.18em] text-[#8b352d]">SIZE &amp; WEIGHT TABLE</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">ตารางขนาดและน้ำหนัก</h2><p className="mt-4 max-w-3xl leading-7 text-zinc-600">ใช้สำหรับเปรียบเทียบขนาดและวางแผนงานเบื้องต้น กดแต่ละขนาดเพื่อดูความหนาและน้ำหนัก</p></Reveal><div className="mt-8 divide-y border">{specifications.map((spec,index)=><details key={spec.size} open={index===0} className="group bg-white"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-4 px-4 py-4 font-black text-[#202124] marker:hidden sm:px-6"><span className="flex items-center gap-3"><span className="text-[#8b352d] transition group-open:rotate-90">▶</span>{spec.size}</span><span className="text-xl text-[#8b352d] group-open:rotate-180">⌄</span></summary><div className="border-t bg-[#f7f6f3] px-4 py-5 sm:px-6"><div className="grid overflow-hidden rounded border bg-white sm:grid-cols-3"><div className="border-b p-4 sm:border-b-0 sm:border-r"><p className="text-xs font-bold text-zinc-500">ความหนา</p><p className="mt-2 text-lg font-black">{spec.thickness}</p></div><div className="border-b p-4 sm:border-b-0 sm:border-r"><p className="text-xs font-bold text-zinc-500">น้ำหนัก</p><p className="mt-2 text-lg font-black text-[#8b352d]">{spec.weight}</p></div><div className="p-4"><p className="text-xs font-bold text-zinc-500">ที่มาของค่า</p><p className="mt-2 text-sm font-bold">{spec.basis}</p></div></div></div></details>)}</div><p className="mt-5 text-sm leading-6 text-zinc-500">หมายเหตุ: น้ำหนักจริงอาจแตกต่างตามค่าความคลาดเคลื่อนของมาตรฐานและผู้ผลิต กรุณาตรวจสอบสเปก ใบรับรอง และน้ำหนักสินค้าจริงกับฝ่ายขายก่อนใช้คำนวณโครงสร้างหรือสั่งซื้อ</p></div></section>
<section className="bg-[#efeeea]"><div className="mx-auto max-w-7xl px-4 sm:px-6 py-12 sm:py-16 lg:py-24"><Reveal><p className="font-black tracking-[.18em] text-[#8b352d]">APPLICATION</p><h2 className="mt-3 text-3xl sm:text-4xl font-black">เหมาะสำหรับงาน</h2></Reveal><Stagger className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{p.uses.map((u,i)=><Item key={u}><div className="border-t-4 border-[#8b352d] bg-white p-6"><span className="text-xs font-black text-zinc-400">0{i+1}</span><h3 className="mt-3 text-lg font-black">{u}</h3></div></Item>)}</Stagger></div></section>
<section className="bg-[#8b352d] text-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-7 px-4 sm:px-6 py-16"><div><p className="text-sm font-bold text-[#f0d8d4]">สนใจ {p.name}?</p><h2 className="mt-2 text-3xl font-black">สอบถามสต๊อก สเปก และราคาได้กับฝ่ายขาย</h2></div><a href="https://lin.ee/Yurg5Hy" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-[#06C755] px-8 py-4 font-black text-white shadow-md transition hover:bg-[#05b34a]"><Image src="/line-logo.svg" alt="" width={22} height={22}/>ขอใบเสนอราคาผ่าน LINE</a></div></section>
</>}
