"use client";
import Link from "next/link"; import Image from "next/image"; import {motion} from "framer-motion"; import {ArrowLeft,ArrowRight,Check,FileText,Phone} from "lucide-react"; import type {Product} from "../data/products"; import {Reveal,Stagger,Item} from "./Motion";
import {useState} from "react";
export default function ProductMotion({product:p}:{product:Product}){const [selectedSize,setSelectedSize]=useState(0);const selectedOption=p.options[selectedSize]??p.options[0];return <>
<section className="bg-[#202124] text-white"><div className="mx-auto max-w-7xl px-4 sm:px-6 py-5"><Link href="/products" className="inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-white"><ArrowLeft size={15}/> สินค้าทั้งหมด / {p.category}</Link></div></section>
<section className="overflow-hidden bg-[#202124] text-white"><div className="mx-auto grid lg:min-h-[610px] max-w-7xl items-center gap-8 lg:gap-14 px-4 sm:px-6 py-16 lg:grid-cols-2">
<div><motion.p initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="font-black tracking-[.2em] text-[#c46b60]">{p.en.toUpperCase()}</motion.p><div className="mt-4 overflow-hidden"><motion.h1 initial={{y:"110%"}} animate={{y:0}} transition={{duration:.75,ease:[.16,1,.3,1]}} className="text-3xl font-black sm:text-5xl lg:text-7xl">{p.name}</motion.h1></div><motion.p initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.22,duration:.65}} className="mt-6 max-w-xl text-lg leading-8 text-zinc-300">{p.short}</motion.p><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.32,duration:.6}} className="mt-6 max-w-md"><label htmlFor="product-size" className="text-sm font-bold text-zinc-300">เลือกขนาด</label><select id="product-size" value={selectedSize} onChange={event=>setSelectedSize(Number(event.target.value))} className="mt-2 w-full border border-white/20 bg-white px-4 py-3 font-bold text-[#202124] outline-none focus:border-[#e47b6e]">{p.options.map((option,index)=><option key={option.size} value={index}>{option.size}</option>)}</select><div className="mt-5 flex items-end justify-between gap-4 border-t border-white/15 pt-5"><span className="pb-1 text-sm font-bold text-zinc-400">ราคา</span><p className="text-4xl font-black text-[#e47b6e]">฿{selectedOption.price.toLocaleString("th-TH")}</p></div></motion.div><motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.45}} className="mt-8 flex flex-col gap-3 text-center sm:flex-row"><Link href="/contact" className="bg-[#8b352d] px-7 py-4 font-black">สอบถามราคา</Link><a href="#detail" className="border border-white/20 px-7 py-4 font-black">ดูรายละเอียด</a></motion.div></div>
<motion.div initial={{opacity:0,scale:.92,x:35}} animate={{opacity:1,scale:1,x:0}} transition={{duration:.85,ease:[.22,1,.36,1]}} className="relative min-h-[280px] overflow-hidden border border-white/10 bg-[#c9c9c9] sm:min-h-[440px]"><Image src={p.image} alt={p.name} fill priority sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover scale-[1.02]"/><div className="absolute bottom-5 left-5 bg-[#202124]/90 px-4 py-2 text-xs font-black tracking-[.15em] text-white backdrop-blur">{p.code} • ภาพประกอบสินค้า</div></motion.div>
</div></section>
<section id="detail" className="scroll-mt-24 mx-auto grid max-w-7xl gap-8 lg:gap-14 px-4 sm:px-6 py-12 sm:py-16 lg:py-24 lg:grid-cols-[1.1fr_.9fr]"><Reveal><p className="font-black tracking-[.18em] text-[#8b352d]">PRODUCT INFORMATION</p><h2 className="mt-3 text-3xl sm:text-4xl font-black">ข้อมูลสินค้า</h2><p className="mt-7 text-lg leading-9 text-zinc-600">{p.description}</p></Reveal><Reveal delay={.12}><div className="border bg-[#f1f0ed] p-5 sm:p-8"><p className="text-xs font-black tracking-[.18em] text-[#8b352d]">SPECIFICATION</p><h3 className="mt-2 text-2xl font-black">ข้อมูลเบื้องต้น</h3><div className="mt-6 space-y-4">{p.specs.map(s=><p key={s} className="flex gap-3 text-zinc-600"><Check className="shrink-0 text-[#8b352d]" size={19}/>{s}</p>)}</div></div></Reveal></section>
<section className="bg-[#efeeea]"><div className="mx-auto max-w-7xl px-4 sm:px-6 py-12 sm:py-16 lg:py-24"><Reveal><p className="font-black tracking-[.18em] text-[#8b352d]">APPLICATION</p><h2 className="mt-3 text-3xl sm:text-4xl font-black">เหมาะสำหรับงาน</h2></Reveal><Stagger className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{p.uses.map((u,i)=><Item key={u}><div className="border-t-4 border-[#8b352d] bg-white p-6"><span className="text-xs font-black text-zinc-400">0{i+1}</span><h3 className="mt-3 text-lg font-black">{u}</h3></div></Item>)}</Stagger></div></section>
<section className="bg-[#8b352d] text-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-7 px-4 sm:px-6 py-16"><div><p className="text-sm font-bold text-[#f0d8d4]">สนใจ {p.name}?</p><h2 className="mt-2 text-3xl font-black">สอบถามสต๊อก สเปก และราคาได้กับฝ่ายขาย</h2></div><Link href="/contact" className="group flex items-center gap-3 bg-white px-8 py-4 font-black text-[#8b352d]">ขอใบเสนอราคา <ArrowRight className="transition group-hover:translate-x-1"/></Link></div></section>
</>}
